/**
 * build-reserved.ts — regenerate the real-title lists (`GeneratorSpec.reservedTitles`) for
 * title-composer and japanese-ln. A draw that reproduces one exactly is rejected and resampled
 * (`engine/generate.ts`, `RESERVED_RETRIES`).
 *
 *   npx tsx tools/titleforge/build-reserved.ts
 *
 * Sources per lexicon:
 *   - its frozen corpora, which its patterns and words were derived from, so they're the titles a
 *     draw is most likely to land on;
 *   - its pattern exemplars (real titles by definition; "(illustrative)" ones are skipped);
 *   - title-composer only: a short curated list of translated classics that its world-fiction
 *     shapes ("{abstractA} and {abstractB}", "{adjective} {subject}") can reach.
 * Each title is reserved as written, without bracketed tails, and as its main title before a
 * colon, since a draw never carries brackets and rarely a subtitle.
 *
 * webnovel's list has its own builder, tied to its hashed corpus
 * (`corpus-webnovel/v1.2.0/build-reserved.mjs`).
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { japaneseLnLexicon } from "../../src/titleforge/lexicons/japaneseLn.js";
import { titleComposerLexicon } from "../../src/titleforge/lexicons/titleComposer.js";
import type { GeneratorSpec } from "../../src/titleforge/engine/types.js";

const here = dirname(fileURLToPath(import.meta.url));
const titleforge = join(here, "../../src/titleforge");

/** Translated classics in the shapes title-composer's world-fiction genres generate. */
const WORLD_CLASSICS = [
	// Russian: paired abstraction, adjective + subject
	"War and Peace", "Crime and Punishment", "Life and Fate", "Fathers and Sons", "Dead Souls", "Poor Folk",
	"The Brothers Karamazov", "The Master and Margarita", "Anna Karenina", "The Idiot", "Demons", "The Gambler",
	"A Hero of Our Time", "Doctor Zhivago", "The Cherry Orchard", "Notes from Underground", "The Possessed",
	"White Nights", "The Double", "Resurrection", "Oblomov", "The Overcoat",
	// Arabic: idafa
	"Season of Migration to the North", "The Thief and the Dogs", "Children of the Alley", "Midaq Alley",
	"Palace Walk", "Palace of Desire", "Sugar Street", "Men in the Sun", "Cities of Salt", "The Map of Love",
	"The Harafish", "The Yacoubian Building",
	// Persian: ezafe
	"The Blind Owl", "The Book of Kings", "The Conference of the Birds", "The Rose Garden", "My Uncle Napoleon",
	"Savushun", "The Colonel",
	// Hindi / Urdu
	"Godan", "The Gift of a Cow", "Nirmala", "Gaban", "Tamas", "Raag Darbari", "The Guide", "Umrao Jaan Ada",
	"River of Fire", "Twilight in Delhi",
	// Swahili and East African
	"Things Fall Apart", "Weep Not, Child", "Petals of Blood", "The River Between", "A Grain of Wheat",
	"Paradise", "Desertion", "By the Sea", "Afterlives", "Rosa Mistika",
];

function sha256(path: string): string {
	return createHash("sha256").update(readFileSync(path)).digest("hex");
}

function readJson(path: string): { records: Record<string, unknown>[] } {
	return JSON.parse(readFileSync(path, "utf8")) as { records: Record<string, unknown>[] };
}

/** Exemplar strings → titles: "A; B" splits; a "native script — English" pair keeps the English. */
function exemplarTitles(spec: GeneratorSpec): string[] {
	const out: string[] = [];
	for (const p of spec.patterns) {
		if (/illustrative/i.test(p.exemplar)) continue;
		for (const part of p.exemplar.split(/;\s*/)) {
			const latin = part.split(/\s+—\s+/).filter((s) => /[A-Za-z]/.test(s)).pop();
			if (!latin) continue;
			// 'Godan, "the gift of a cow"' → Godan; strip wrapping quotes.
			const cleaned = latin.replace(/,\s*["“].*$/, "").replace(/^["“'‘]|["”'’]$/g, "").trim();
			if (cleaned) out.push(cleaned);
		}
	}
	return out;
}

/** A title as written, without bracketed tails, and as its main title before a colon. */
function variants(title: string): string[] {
	const forms = new Set<string>([title.trim()]);
	const bracketFree = title.replace(/\s*[([][^)\]]*[)\]]\s*/g, " ").replace(/\s+/g, " ").trim();
	forms.add(bracketFree);
	const colon = bracketFree.indexOf(":");
	if (colon > 0) forms.add(bracketFree.slice(0, colon).trim());
	return [...forms].filter((f) => f.length > 0);
}

function write(file: string, exportName: string, sources: string[], titles: Iterable<string>): number {
	const all = new Set<string>();
	for (const t of titles) for (const v of variants(t)) all.add(v);
	const sorted = [...all].sort((a, b) => a.localeCompare(b));
	writeFileSync(
		join(titleforge, "lexicons", file),
		`// GENERATED by tools/titleforge/build-reserved.ts — do not edit by hand.\n` +
			sources.map((s) => `// Source: ${s}\n`).join("") +
			`\n/** Real titles this generator must never reproduce (\`GeneratorSpec.reservedTitles\`). */\n` +
			`export const ${exportName}: readonly string[] = ${JSON.stringify(sorted, null, "\t")};\n`,
	);
	return sorted.length;
}

const seriesPath = join(titleforge, "corpus/corpus.core.frozen.json");
const novelPath = join(titleforge, "corpus-novel/corpus.core.frozen.json");
const jplnPath = join(titleforge, "corpus-jpln/corpus.v1.4.0.frozen.json");

const series = readJson(seriesPath).records.flatMap((r) => [
	String(r.canonical_series_name),
	...((r.aliases as string[] | undefined) ?? []),
]);
const novels = readJson(novelPath).records.map((r) => String(r.title));
const tc = write(
	"titleComposerReserved.ts",
	"titleComposerReservedTitles",
	[
		`corpus/corpus.core.frozen.json sha256 ${sha256(seriesPath)} (series names + aliases)`,
		`corpus-novel/corpus.core.frozen.json sha256 ${sha256(novelPath)} (novel titles)`,
		"title-composer pattern exemplars",
		"tools/titleforge/build-reserved.ts WORLD_CLASSICS (translated classics in world-fiction shapes)",
	],
	[...series, ...novels, ...exemplarTitles(titleComposerLexicon), ...WORLD_CLASSICS],
);

const jpln = readJson(jplnPath).records.map((r) => String(r.title));
const jl = write(
	"japaneseLnReserved.ts",
	"japaneseLnReservedTitles",
	[`corpus-jpln/corpus.v1.4.0.frozen.json sha256 ${sha256(jplnPath)}`, "japanese-ln pattern exemplars"],
	[...jpln, ...exemplarTitles(japaneseLnLexicon)],
);

console.log(`title-composer: ${tc} reserved titles; japanese-ln: ${jl}`);
