/**
 * vocab-pools.mjs — review report for the additive vocabulary model.
 *
 * For every bundled lexicon, genre and slot the genre's patterns actually use, compares the pool
 * a draw sees today (additive: own + ancestors' lexicons + general list) against the older
 * exclusive narrowing (reproduced by marking every slot exclusive). Also lists what each
 * promotion rule promotes, the untagged entries (general by definition, so each needs a yes/no),
 * and sample titles per genre.
 *
 *   npx tsx tools/titleforge/vocab-pools.mjs       (or `npm run titleforge:pools`)
 *
 * Writes `tools/titleforge/VOCAB-POOLS.md`.
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
	ancestorIds,
	eligiblePatterns,
	generateMany,
	inParentLexicon,
	isGeneralEntry,
	isParent,
	scopedLexicon,
} from "../../src/titleforge/engine/generate.ts";
import { normaliseLexicon } from "../../src/titleforge/engine/lexicon.ts";
import { slotsIn } from "../../src/titleforge/engine/template.ts";
import { ALL_TITLEFORGE_LEXICONS } from "../../src/titleforge/lexicons/index.ts";

/** @typedef {import("../../src/titleforge/engine/types.ts").GeneratorSpec} GeneratorSpec */

/** A pool under this many words is reported as thin. */
export const THIN_POOL = 8;
const SAMPLES_PER_GENRE = 10;

/**
 * Slots the patterns eligible under `genreId` actually draw from.
 * @param {GeneratorSpec} spec
 * @param {string} genreId
 * @returns {string[]}
 */
export function usedSlots(spec, genreId) {
	/** @type {Set<string>} */
	const slots = new Set();
	for (const p of eligiblePatterns(spec, { genre: genreId })) {
		for (const t of p.templates) for (const s of slotsIn(t)) slots.add(s);
	}
	return [...slots].filter((s) => spec.lexicon[s]).sort();
}

/**
 * A pool's effective size: its entry count, or Infinity when it can invent names (an `@register`
 * entry is an unlimited supply, not one word).
 * @param {readonly { generator?: string }[] | undefined} pool
 * @returns {number}
 */
export function poolSize(pool) {
	if (!pool) return 0;
	return pool.some((e) => e.generator) ? Infinity : pool.length;
}

/**
 * The same spec with every slot exclusive — how a draw scoped before the additive model.
 * @param {GeneratorSpec} spec
 * @returns {GeneratorSpec}
 */
function exclusiveTwin(spec) {
	return { ...spec, exclusiveSlots: Object.keys(spec.lexicon) };
}

/** @param {string} s */
const md = (s) => s.replace(/\|/g, "\\|");

/** @returns {string} */
function report() {
	/** @type {string[]} */
	const out = [
		"# titleForge vocabulary pools — additive model review",
		"",
		"Generated by `tools/titleforge/vocab-pools.mjs`. **Before** is the older exclusive narrowing " +
			"(one tagged word made a slot exclusive); **after** is the additive model: the genre's own words, " +
			"plus each ancestor's lexicon (entries tagged with the parent or with 2+ of its subgenres), plus " +
			"the general list (entries spanning 2+ top-level genres, or untagged).",
		"",
		"## Summary",
		"",
		`| Lexicon | Genres | Thin cells before (< ${THIN_POOL}) | Thin cells after | General-list entries | Untagged |`,
		"|---|--:|--:|--:|--:|--:|",
	];
	/** @type {string[]} */
	const sections = [];

	for (const spec of ALL_TITLEFORGE_LEXICONS) {
		const base = normaliseLexicon(spec.lexicon);
		const twin = exclusiveTwin(spec);
		const genres = spec.genres.filter((g) => g.id !== "all");
		let thinBefore = 0;
		let thinAfter = 0;
		/** @type {string[]} */
		const cells = [];
		for (const g of genres) {
			const before = scopedLexicon(twin, g.id);
			const after = scopedLexicon(spec, g.id);
			for (const slot of usedSlots(spec, g.id)) {
				const b = poolSize(before[slot]);
				const a = poolSize(after[slot]);
				if (b < THIN_POOL) thinBefore++;
				if (a < THIN_POOL) thinAfter++;
				/** @param {number} n */
				const show = (n) => (n === Infinity ? "invented" : String(n));
				if (b < THIN_POOL || a < THIN_POOL) cells.push(`| ${g.id} | ${slot} | ${show(b)} | ${show(a)} |${a < THIN_POOL ? " **thin**" : ""} |`);
			}
		}

		// Promotion listings.
		/** @type {string[]} */
		const general = [];
		/** @type {string[]} */
		const untagged = [];
		/** @type {string[]} */
		const parentPromos = [];
		const parents = spec.genres.filter((g) => isParent(spec, g.id));
		for (const [slot, entries] of Object.entries(base)) {
			const autoGeneral = entries.filter((e) => e.tags?.length && isGeneralEntry(spec, e.tags));
			const bare = entries.filter((e) => !e.tags?.length);
			const tagged = entries.some((e) => e.tags?.length);
			if (autoGeneral.length) general.push(`- **${slot}** (${autoGeneral.length}): ${autoGeneral.map((e) => `${md(e.gloss)} [${(e.tags ?? []).join(", ")}]`).join(" · ")}`);
			if (bare.length && tagged) untagged.push(`- **${slot}** (${bare.length}): ${bare.map((e) => md(e.gloss)).join(", ")}`);
			for (const p of parents) {
				const promoted = entries.filter((e) => !(e.tags ?? []).includes(p.id) && inParentLexicon(spec, e.tags, p.id));
				if (promoted.length) parentPromos.push(`- **${slot} → ${p.id}** (${promoted.length}): ${promoted.map((e) => md(e.gloss)).join(", ")}`);
			}
		}
		const generalCount = Object.values(base).flat().filter((e) => isGeneralEntry(spec, e.tags)).length;
		const untaggedCount = Object.values(base).flat().filter((e) => !e.tags?.length).length;
		out.push(`| ${spec.id} | ${genres.length} | ${thinBefore} | ${thinAfter} | ${generalCount} | ${untaggedCount} |`);

		const samples = genres.map((g) => {
			const lineage = [g.id, ...ancestorIds(spec, g.id)].reverse().join(" › ");
			const titles = generateMany(spec, SAMPLES_PER_GENRE, { genre: g.id, seed: 2026 }).map((r) => md(r.title));
			return `- **${lineage}**: ${titles.join(" · ")}`;
		});

		sections.push(
			`## ${spec.id}`,
			"",
			`### Pools that were or are still thin (< ${THIN_POOL})`,
			"",
			cells.length ? "| Genre | Slot | Before | After | |\n|---|---|--:|--:|---|\n" + cells.join("\n") : "_none_",
			"",
			"### Promoted to the general list (tags span 2+ top-level genres)",
			"",
			general.length ? general.join("\n") : "_none_",
			"",
			"### Untagged entries in tagged slots (general by definition — audit each)",
			"",
			untagged.length ? untagged.join("\n") : "_none_",
			"",
			"### Promoted into a parent's lexicon (tagged with 2+ of its subgenres)",
			"",
			parentPromos.length ? parentPromos.join("\n") : "_none_",
			"",
			`### Samples (${SAMPLES_PER_GENRE} per genre, seed 2026)`,
			"",
			...samples,
			"",
		);
	}
	return [...out, "", ...sections].join("\n");
}

// Run only as a script, never on import (the coverage tool reuses `usedSlots`).
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
	const target = join(dirname(fileURLToPath(import.meta.url)), "VOCAB-POOLS.md");
	writeFileSync(target, report());
	console.log(`wrote ${target}`);
}

