// Hand-maintained colour palettes from each theme's canonical sources.
// Sources:
// - Atom: https://github.com/atom/one-dark-syntax + https://github.com/atom/one-light-syntax
// - Ayu: https://github.com/ayu-theme/ayu-colors
// - Catppuccin: https://github.com/catppuccin/catppuccin
// - Dracula: https://draculatheme.com + https://github.com/dracula/dracula-theme
// - Everforest: https://github.com/sainnhe/everforest
// - Flexoki: https://github.com/kepano/flexoki
// - Gruvbox: https://github.com/morhetz/gruvbox
// - Nord: https://www.nordtheme.com/docs/colors-and-palettes
// - Rosé Pine: https://github.com/rose-pine/rose-pine
// - Solarized: https://ethanschoonover.com/solarized + https://github.com/altercation/solarized

export type PaletteMode = "light" | "dark";

export type PresetPaletteName =
	| "Atom"
	| "Ayu"
	| "Catppuccin"
	| "Dracula"
	| "Everforest"
	| "Flexoki"
	| "Gruvbox"
	| "Nord"
	| "Rosé Pine"
	| "Solarized";

export type PaletteName = PresetPaletteName | "Custom";

/** Custom is listed last; it is the default palette and the user-editable colour set. */
export const PALETTE_NAMES: PaletteName[] = [
	"Atom",
	"Ayu",
	"Catppuccin",
	"Dracula",
	"Everforest",
	"Flexoki",
	"Gruvbox",
	"Nord",
	"Rosé Pine",
	"Solarized",
	"Custom",
];

export interface PaletteColor {
	name: string;
	hex: string;
}

export interface PaletteVariant {
	name: string;
	appearance: PaletteMode;
	source: string;
	colors: PaletteColor[];
}

export const COLOR_PALETTES: Record<PresetPaletteName, PaletteVariant[]> = {
	Atom: [
		{
			name: "Light",
			appearance: "light",
			source: "https://github.com/atom/one-light-syntax",
			colors: [
			{ name: "Background", hex: "#fafafa" },
			{ name: "Foreground", hex: "#383a42" },
			{ name: "Mono 2", hex: "#696c77" },
			{ name: "Mono 3", hex: "#a0a1a7" },
			{ name: "Cyan", hex: "#0184bc" },
			{ name: "Blue", hex: "#4078f2" },
			{ name: "Purple", hex: "#a626a4" },
			{ name: "Green", hex: "#50a14f" },
			{ name: "Red", hex: "#e45649" },
			{ name: "Dark Red", hex: "#ca1243" },
			{ name: "Orange", hex: "#986801" },
			{ name: "Yellow", hex: "#c18401" },
			{ name: "Accent", hex: "#526eff" },
			],
		},
		{
			name: "Dark",
			appearance: "dark",
			source: "https://github.com/atom/one-dark-syntax",
			colors: [
			{ name: "Background", hex: "#282c34" },
			{ name: "Foreground", hex: "#abb2bf" },
			{ name: "Mono 2", hex: "#828997" },
			{ name: "Mono 3", hex: "#5c6370" },
			{ name: "Cyan", hex: "#56b6c2" },
			{ name: "Blue", hex: "#61afef" },
			{ name: "Purple", hex: "#c678dd" },
			{ name: "Green", hex: "#98c379" },
			{ name: "Red", hex: "#e06c75" },
			{ name: "Dark Red", hex: "#be5046" },
			{ name: "Orange", hex: "#d19a66" },
			{ name: "Yellow", hex: "#e5c07b" },
			{ name: "Accent", hex: "#528bff" },
			],
		},
	],
	Ayu: [
		{
			name: "Light",
			appearance: "light",
			source: "https://github.com/ayu-theme/ayu-colors",
			colors: [
			{ name: "Editor Background", hex: "#fcfcfc" },
			{ name: "Editor Foreground", hex: "#5c6166" },
			{ name: "UI Background", hex: "#f8f9fa" },
			{ name: "UI Foreground", hex: "#8a9199" },
			{ name: "Accent", hex: "#ffaa33" },
			{ name: "Error", hex: "#e65050" },
			{ name: "Tag", hex: "#55b4d4" },
			{ name: "Func", hex: "#f2ae49" },
			{ name: "Entity", hex: "#399ee6" },
			{ name: "String", hex: "#86b300" },
			{ name: "Regexp", hex: "#4cbf99" },
			{ name: "Markup", hex: "#f07171" },
			{ name: "Keyword", hex: "#fa8d3e" },
			{ name: "Special", hex: "#e6ba7e" },
			{ name: "Constant", hex: "#a37acc" },
			{ name: "Operator", hex: "#ed9366" },
			{ name: "Added", hex: "#6cbf43" },
			{ name: "Modified", hex: "#478acc" },
			{ name: "Removed", hex: "#ff7383" },
			],
		},
		{
			name: "Mirage",
			appearance: "dark",
			source: "https://github.com/ayu-theme/ayu-colors",
			colors: [
			{ name: "Editor Background", hex: "#242936" },
			{ name: "Editor Foreground", hex: "#cccac2" },
			{ name: "UI Background", hex: "#1f2430" },
			{ name: "UI Foreground", hex: "#707a8c" },
			{ name: "Accent", hex: "#ffcc66" },
			{ name: "Error", hex: "#ff6666" },
			{ name: "Tag", hex: "#5ccfe6" },
			{ name: "Func", hex: "#ffd173" },
			{ name: "Entity", hex: "#73d0ff" },
			{ name: "String", hex: "#d5ff80" },
			{ name: "Regexp", hex: "#95e6cb" },
			{ name: "Markup", hex: "#f28779" },
			{ name: "Keyword", hex: "#ffad66" },
			{ name: "Special", hex: "#ffdfb3" },
			{ name: "Constant", hex: "#dfbfff" },
			{ name: "Operator", hex: "#f29e74" },
			{ name: "Added", hex: "#87d96c" },
			{ name: "Modified", hex: "#80bfff" },
			{ name: "Removed", hex: "#f27983" },
			],
		},
		{
			name: "Dark",
			appearance: "dark",
			source: "https://github.com/ayu-theme/ayu-colors",
			colors: [
			{ name: "Editor Background", hex: "#0d1017" },
			{ name: "Editor Foreground", hex: "#bfbdb6" },
			{ name: "UI Background", hex: "#0b0e14" },
			{ name: "UI Foreground", hex: "#565b66" },
			{ name: "Accent", hex: "#e6b450" },
			{ name: "Error", hex: "#d95757" },
			{ name: "Tag", hex: "#39bae6" },
			{ name: "Func", hex: "#ffb454" },
			{ name: "Entity", hex: "#59c2ff" },
			{ name: "String", hex: "#aad94c" },
			{ name: "Regexp", hex: "#95e6cb" },
			{ name: "Markup", hex: "#f07178" },
			{ name: "Keyword", hex: "#ff8f40" },
			{ name: "Special", hex: "#e6b673" },
			{ name: "Constant", hex: "#d2a6ff" },
			{ name: "Operator", hex: "#f29668" },
			{ name: "Added", hex: "#7fd962" },
			{ name: "Modified", hex: "#73b8ff" },
			{ name: "Removed", hex: "#f26d78" },
			],
		},
	],
	Catppuccin: [
		{
			name: "Latte",
			appearance: "light",
			source: "https://github.com/catppuccin/catppuccin",
			colors: [
			{ name: "Rosewater", hex: "#dc8a78" },
			{ name: "Flamingo", hex: "#dd7878" },
			{ name: "Pink", hex: "#ea76cb" },
			{ name: "Mauve", hex: "#8839ef" },
			{ name: "Red", hex: "#d20f39" },
			{ name: "Maroon", hex: "#e64553" },
			{ name: "Peach", hex: "#fe640b" },
			{ name: "Yellow", hex: "#df8e1d" },
			{ name: "Green", hex: "#40a02b" },
			{ name: "Teal", hex: "#179299" },
			{ name: "Sky", hex: "#04a5e5" },
			{ name: "Sapphire", hex: "#209fb5" },
			{ name: "Blue", hex: "#1e66f5" },
			{ name: "Lavender", hex: "#7287fd" },
			{ name: "Text", hex: "#4c4f69" },
			{ name: "Subtext 1", hex: "#5c5f77" },
			{ name: "Subtext 0", hex: "#6c6f85" },
			{ name: "Overlay 2", hex: "#7c7f93" },
			{ name: "Overlay 1", hex: "#8c8fa1" },
			{ name: "Overlay 0", hex: "#9ca0b0" },
			{ name: "Surface 2", hex: "#acb0be" },
			{ name: "Surface 1", hex: "#bcc0cc" },
			{ name: "Surface 0", hex: "#ccd0da" },
			{ name: "Base", hex: "#eff1f5" },
			{ name: "Mantle", hex: "#e6e9ef" },
			{ name: "Crust", hex: "#dce0e8" },
			],
		},
		{
			name: "Frappé",
			appearance: "dark",
			source: "https://github.com/catppuccin/catppuccin",
			colors: [
			{ name: "Rosewater", hex: "#f2d5cf" },
			{ name: "Flamingo", hex: "#eebebe" },
			{ name: "Pink", hex: "#f4b8e4" },
			{ name: "Mauve", hex: "#ca9ee6" },
			{ name: "Red", hex: "#e78284" },
			{ name: "Maroon", hex: "#ea999c" },
			{ name: "Peach", hex: "#ef9f76" },
			{ name: "Yellow", hex: "#e5c890" },
			{ name: "Green", hex: "#a6d189" },
			{ name: "Teal", hex: "#81c8be" },
			{ name: "Sky", hex: "#99d1db" },
			{ name: "Sapphire", hex: "#85c1dc" },
			{ name: "Blue", hex: "#8caaee" },
			{ name: "Lavender", hex: "#babbf1" },
			{ name: "Text", hex: "#c6d0f5" },
			{ name: "Subtext 1", hex: "#b5bfe2" },
			{ name: "Subtext 0", hex: "#a5adce" },
			{ name: "Overlay 2", hex: "#949cbb" },
			{ name: "Overlay 1", hex: "#838ba7" },
			{ name: "Overlay 0", hex: "#737994" },
			{ name: "Surface 2", hex: "#626880" },
			{ name: "Surface 1", hex: "#51576d" },
			{ name: "Surface 0", hex: "#414559" },
			{ name: "Base", hex: "#303446" },
			{ name: "Mantle", hex: "#292c3c" },
			{ name: "Crust", hex: "#232634" },
			],
		},
		{
			name: "Macchiato",
			appearance: "dark",
			source: "https://github.com/catppuccin/catppuccin",
			colors: [
			{ name: "Rosewater", hex: "#f4dbd6" },
			{ name: "Flamingo", hex: "#f0c6c6" },
			{ name: "Pink", hex: "#f5bde6" },
			{ name: "Mauve", hex: "#c6a0f6" },
			{ name: "Red", hex: "#ed8796" },
			{ name: "Maroon", hex: "#ee99a0" },
			{ name: "Peach", hex: "#f5a97f" },
			{ name: "Yellow", hex: "#eed49f" },
			{ name: "Green", hex: "#a6da95" },
			{ name: "Teal", hex: "#8bd5ca" },
			{ name: "Sky", hex: "#91d7e3" },
			{ name: "Sapphire", hex: "#7dc4e4" },
			{ name: "Blue", hex: "#8aadf4" },
			{ name: "Lavender", hex: "#b7bdf8" },
			{ name: "Text", hex: "#cad3f5" },
			{ name: "Subtext 1", hex: "#b8c0e0" },
			{ name: "Subtext 0", hex: "#a5adcb" },
			{ name: "Overlay 2", hex: "#939ab7" },
			{ name: "Overlay 1", hex: "#8087a2" },
			{ name: "Overlay 0", hex: "#6e738d" },
			{ name: "Surface 2", hex: "#5b6078" },
			{ name: "Surface 1", hex: "#494d64" },
			{ name: "Surface 0", hex: "#363a4f" },
			{ name: "Base", hex: "#24273a" },
			{ name: "Mantle", hex: "#1e2030" },
			{ name: "Crust", hex: "#181926" },
			],
		},
		{
			name: "Mocha",
			appearance: "dark",
			source: "https://github.com/catppuccin/catppuccin",
			colors: [
			{ name: "Rosewater", hex: "#f5e0dc" },
			{ name: "Flamingo", hex: "#f2cdcd" },
			{ name: "Pink", hex: "#f5c2e7" },
			{ name: "Mauve", hex: "#cba6f7" },
			{ name: "Red", hex: "#f38ba8" },
			{ name: "Maroon", hex: "#eba0ac" },
			{ name: "Peach", hex: "#fab387" },
			{ name: "Yellow", hex: "#f9e2af" },
			{ name: "Green", hex: "#a6e3a1" },
			{ name: "Teal", hex: "#94e2d5" },
			{ name: "Sky", hex: "#89dceb" },
			{ name: "Sapphire", hex: "#74c7ec" },
			{ name: "Blue", hex: "#89b4fa" },
			{ name: "Lavender", hex: "#b4befe" },
			{ name: "Text", hex: "#cdd6f4" },
			{ name: "Subtext 1", hex: "#bac2de" },
			{ name: "Subtext 0", hex: "#a6adc8" },
			{ name: "Overlay 2", hex: "#9399b2" },
			{ name: "Overlay 1", hex: "#7f849c" },
			{ name: "Overlay 0", hex: "#6c7086" },
			{ name: "Surface 2", hex: "#585b70" },
			{ name: "Surface 1", hex: "#45475a" },
			{ name: "Surface 0", hex: "#313244" },
			{ name: "Base", hex: "#1e1e2e" },
			{ name: "Mantle", hex: "#181825" },
			{ name: "Crust", hex: "#11111b" },
			],
		},
	],
	Dracula: [
		{
			name: "Dracula",
			appearance: "dark",
			source: "https://github.com/dracula/dracula-theme",
			colors: [
			{ name: "Background", hex: "#282a36" },
			{ name: "Current Line", hex: "#44475a" },
			{ name: "Selection", hex: "#44475a" },
			{ name: "Foreground", hex: "#f8f8f2" },
			{ name: "Comment", hex: "#6272a4" },
			{ name: "Cyan", hex: "#8be9fd" },
			{ name: "Green", hex: "#50fa7b" },
			{ name: "Orange", hex: "#ffb86c" },
			{ name: "Pink", hex: "#ff79c6" },
			{ name: "Purple", hex: "#bd93f9" },
			{ name: "Red", hex: "#ff5555" },
			{ name: "Yellow", hex: "#f1fa8c" },
			],
		},
	],
	Everforest: [
		{
			name: "Hard Light",
			appearance: "light",
			source: "https://github.com/sainnhe/everforest",
			colors: [
			{ name: "bg_dim", hex: "#f2efdf" },
			{ name: "bg0", hex: "#fffbef" },
			{ name: "bg1", hex: "#f8f5e4" },
			{ name: "bg2", hex: "#f2efdf" },
			{ name: "bg3", hex: "#edeada" },
			{ name: "bg4", hex: "#e8e5d5" },
			{ name: "bg5", hex: "#bec5b2" },
			{ name: "bg_visual", hex: "#f0f2d4" },
			{ name: "bg_red", hex: "#ffe7de" },
			{ name: "bg_yellow", hex: "#fef2d5" },
			{ name: "bg_green", hex: "#f3f5d9" },
			{ name: "bg_blue", hex: "#ecf5ed" },
			{ name: "bg_purple", hex: "#fceced" },
			{ name: "fg", hex: "#5c6a72" },
			{ name: "red", hex: "#f85552" },
			{ name: "orange", hex: "#f57d26" },
			{ name: "yellow", hex: "#dfa000" },
			{ name: "green", hex: "#8da101" },
			{ name: "aqua", hex: "#35a77c" },
			{ name: "blue", hex: "#3a94c5" },
			{ name: "purple", hex: "#df69ba" },
			{ name: "grey0", hex: "#a6b0a0" },
			{ name: "grey1", hex: "#939f91" },
			{ name: "grey2", hex: "#829181" },
			{ name: "statusline1", hex: "#93b259" },
			{ name: "statusline2", hex: "#708089" },
			{ name: "statusline3", hex: "#e66868" },
			],
		},
		{
			name: "Medium Light",
			appearance: "light",
			source: "https://github.com/sainnhe/everforest",
			colors: [
			{ name: "bg_dim", hex: "#efebd4" },
			{ name: "bg0", hex: "#fdf6e3" },
			{ name: "bg1", hex: "#f4f0d9" },
			{ name: "bg2", hex: "#efebd4" },
			{ name: "bg3", hex: "#e6e2cc" },
			{ name: "bg4", hex: "#e0dcc7" },
			{ name: "bg5", hex: "#bdc3af" },
			{ name: "bg_visual", hex: "#eaedc8" },
			{ name: "bg_red", hex: "#fde3da" },
			{ name: "bg_yellow", hex: "#faedcd" },
			{ name: "bg_green", hex: "#f0f1d2" },
			{ name: "bg_blue", hex: "#e9f0e9" },
			{ name: "bg_purple", hex: "#fae8e2" },
			{ name: "fg", hex: "#5c6a72" },
			{ name: "red", hex: "#f85552" },
			{ name: "orange", hex: "#f57d26" },
			{ name: "yellow", hex: "#dfa000" },
			{ name: "green", hex: "#8da101" },
			{ name: "aqua", hex: "#35a77c" },
			{ name: "blue", hex: "#3a94c5" },
			{ name: "purple", hex: "#df69ba" },
			{ name: "grey0", hex: "#a6b0a0" },
			{ name: "grey1", hex: "#939f91" },
			{ name: "grey2", hex: "#829181" },
			{ name: "statusline1", hex: "#93b259" },
			{ name: "statusline2", hex: "#708089" },
			{ name: "statusline3", hex: "#e66868" },
			],
		},
		{
			name: "Soft Light",
			appearance: "light",
			source: "https://github.com/sainnhe/everforest",
			colors: [
			{ name: "bg_dim", hex: "#e5dfc5" },
			{ name: "bg0", hex: "#f3ead3" },
			{ name: "bg1", hex: "#eae4ca" },
			{ name: "bg2", hex: "#e5dfc5" },
			{ name: "bg3", hex: "#ddd8be" },
			{ name: "bg4", hex: "#d8d3ba" },
			{ name: "bg5", hex: "#b9c0ab" },
			{ name: "bg_visual", hex: "#e1e4bd" },
			{ name: "bg_red", hex: "#fadbd0" },
			{ name: "bg_yellow", hex: "#f1e4c5" },
			{ name: "bg_green", hex: "#e5e6c5" },
			{ name: "bg_blue", hex: "#e1e7dd" },
			{ name: "bg_purple", hex: "#f1ddd4" },
			{ name: "fg", hex: "#5c6a72" },
			{ name: "red", hex: "#f85552" },
			{ name: "orange", hex: "#f57d26" },
			{ name: "yellow", hex: "#dfa000" },
			{ name: "green", hex: "#8da101" },
			{ name: "aqua", hex: "#35a77c" },
			{ name: "blue", hex: "#3a94c5" },
			{ name: "purple", hex: "#df69ba" },
			{ name: "grey0", hex: "#a6b0a0" },
			{ name: "grey1", hex: "#939f91" },
			{ name: "grey2", hex: "#829181" },
			{ name: "statusline1", hex: "#93b259" },
			{ name: "statusline2", hex: "#708089" },
			{ name: "statusline3", hex: "#e66868" },
			],
		},
		{
			name: "Hard Dark",
			appearance: "dark",
			source: "https://github.com/sainnhe/everforest",
			colors: [
			{ name: "bg_dim", hex: "#1e2326" },
			{ name: "bg0", hex: "#272e33" },
			{ name: "bg1", hex: "#2e383c" },
			{ name: "bg2", hex: "#374145" },
			{ name: "bg3", hex: "#414b50" },
			{ name: "bg4", hex: "#495156" },
			{ name: "bg5", hex: "#4f5b58" },
			{ name: "bg_visual", hex: "#4c3743" },
			{ name: "bg_red", hex: "#493b40" },
			{ name: "bg_yellow", hex: "#45443c" },
			{ name: "bg_green", hex: "#3c4841" },
			{ name: "bg_blue", hex: "#384b55" },
			{ name: "bg_purple", hex: "#463f48" },
			{ name: "fg", hex: "#d3c6aa" },
			{ name: "red", hex: "#e67e80" },
			{ name: "orange", hex: "#e69875" },
			{ name: "yellow", hex: "#dbbc7f" },
			{ name: "green", hex: "#a7c080" },
			{ name: "aqua", hex: "#83c092" },
			{ name: "blue", hex: "#7fbbb3" },
			{ name: "purple", hex: "#d699b6" },
			{ name: "grey0", hex: "#7a8478" },
			{ name: "grey1", hex: "#859289" },
			{ name: "grey2", hex: "#9da9a0" },
			{ name: "statusline1", hex: "#a7c080" },
			{ name: "statusline2", hex: "#d3c6aa" },
			{ name: "statusline3", hex: "#e67e80" },
			],
		},
		{
			name: "Medium Dark",
			appearance: "dark",
			source: "https://github.com/sainnhe/everforest",
			colors: [
			{ name: "bg_dim", hex: "#232a2e" },
			{ name: "bg0", hex: "#2d353b" },
			{ name: "bg1", hex: "#343f44" },
			{ name: "bg2", hex: "#3d484d" },
			{ name: "bg3", hex: "#475258" },
			{ name: "bg4", hex: "#4f585e" },
			{ name: "bg5", hex: "#56635f" },
			{ name: "bg_visual", hex: "#543a48" },
			{ name: "bg_red", hex: "#514045" },
			{ name: "bg_yellow", hex: "#4d4c43" },
			{ name: "bg_green", hex: "#425047" },
			{ name: "bg_blue", hex: "#3a515d" },
			{ name: "bg_purple", hex: "#4a444e" },
			{ name: "fg", hex: "#d3c6aa" },
			{ name: "red", hex: "#e67e80" },
			{ name: "orange", hex: "#e69875" },
			{ name: "yellow", hex: "#dbbc7f" },
			{ name: "green", hex: "#a7c080" },
			{ name: "aqua", hex: "#83c092" },
			{ name: "blue", hex: "#7fbbb3" },
			{ name: "purple", hex: "#d699b6" },
			{ name: "grey0", hex: "#7a8478" },
			{ name: "grey1", hex: "#859289" },
			{ name: "grey2", hex: "#9da9a0" },
			{ name: "statusline1", hex: "#a7c080" },
			{ name: "statusline2", hex: "#d3c6aa" },
			{ name: "statusline3", hex: "#e67e80" },
			],
		},
		{
			name: "Soft Dark",
			appearance: "dark",
			source: "https://github.com/sainnhe/everforest",
			colors: [
			{ name: "bg_dim", hex: "#293136" },
			{ name: "bg0", hex: "#333c43" },
			{ name: "bg1", hex: "#3a464c" },
			{ name: "bg2", hex: "#434f55" },
			{ name: "bg3", hex: "#4d5960" },
			{ name: "bg4", hex: "#555f66" },
			{ name: "bg5", hex: "#5d6b66" },
			{ name: "bg_visual", hex: "#5c3f4f" },
			{ name: "bg_red", hex: "#59464c" },
			{ name: "bg_yellow", hex: "#55544a" },
			{ name: "bg_green", hex: "#48584e" },
			{ name: "bg_blue", hex: "#3f5865" },
			{ name: "bg_purple", hex: "#4e4953" },
			{ name: "fg", hex: "#d3c6aa" },
			{ name: "red", hex: "#e67e80" },
			{ name: "orange", hex: "#e69875" },
			{ name: "yellow", hex: "#dbbc7f" },
			{ name: "green", hex: "#a7c080" },
			{ name: "aqua", hex: "#83c092" },
			{ name: "blue", hex: "#7fbbb3" },
			{ name: "purple", hex: "#d699b6" },
			{ name: "grey0", hex: "#7a8478" },
			{ name: "grey1", hex: "#859289" },
			{ name: "grey2", hex: "#9da9a0" },
			{ name: "statusline1", hex: "#a7c080" },
			{ name: "statusline2", hex: "#d3c6aa" },
			{ name: "statusline3", hex: "#e67e80" },
			],
		},
	],
	Flexoki: [
		{
			name: "Light",
			appearance: "light",
			source: "https://github.com/kepano/flexoki",
			colors: [
			{ name: "black", hex: "#100f0f" },
			{ name: "paper", hex: "#fffcf0" },
			{ name: "base-50", hex: "#f2f0e5" },
			{ name: "base-100", hex: "#e6e4d9" },
			{ name: "base-150", hex: "#dad8ce" },
			{ name: "base-200", hex: "#cecdc3" },
			{ name: "base-300", hex: "#b7b5ac" },
			{ name: "base-400", hex: "#9f9d96" },
			{ name: "base-500", hex: "#878580" },
			{ name: "base-600", hex: "#6f6e69" },
			{ name: "base-700", hex: "#575653" },
			{ name: "base-800", hex: "#403e3c" },
			{ name: "base-850", hex: "#343331" },
			{ name: "base-900", hex: "#282726" },
			{ name: "base-950", hex: "#1c1b1a" },
			{ name: "red", hex: "#af3029" },
			{ name: "orange", hex: "#bc5215" },
			{ name: "yellow", hex: "#ad8301" },
			{ name: "green", hex: "#66800b" },
			{ name: "cyan", hex: "#24837b" },
			{ name: "blue", hex: "#205ea6" },
			{ name: "purple", hex: "#5e409d" },
			{ name: "magenta", hex: "#a02f6f" },
			],
		},
		{
			name: "Dark",
			appearance: "dark",
			source: "https://github.com/kepano/flexoki",
			colors: [
			{ name: "black", hex: "#100f0f" },
			{ name: "paper", hex: "#fffcf0" },
			{ name: "base-50", hex: "#f2f0e5" },
			{ name: "base-100", hex: "#e6e4d9" },
			{ name: "base-150", hex: "#dad8ce" },
			{ name: "base-200", hex: "#cecdc3" },
			{ name: "base-300", hex: "#b7b5ac" },
			{ name: "base-400", hex: "#9f9d96" },
			{ name: "base-500", hex: "#878580" },
			{ name: "base-600", hex: "#6f6e69" },
			{ name: "base-700", hex: "#575653" },
			{ name: "base-800", hex: "#403e3c" },
			{ name: "base-850", hex: "#343331" },
			{ name: "base-900", hex: "#282726" },
			{ name: "base-950", hex: "#1c1b1a" },
			{ name: "red", hex: "#d14d41" },
			{ name: "orange", hex: "#da702c" },
			{ name: "yellow", hex: "#d0a215" },
			{ name: "green", hex: "#879a39" },
			{ name: "cyan", hex: "#3aa99f" },
			{ name: "blue", hex: "#4385be" },
			{ name: "purple", hex: "#8b7ec8" },
			{ name: "magenta", hex: "#ce5d97" },
			],
		},
	],
	Gruvbox: [
		{
			name: "Hard Light",
			appearance: "light",
			source: "https://github.com/morhetz/gruvbox",
			colors: [
			{ name: "light0_hard", hex: "#f9f5d7" },
			{ name: "light1", hex: "#ebdbb2" },
			{ name: "light2", hex: "#d5c4a1" },
			{ name: "light3", hex: "#bdae93" },
			{ name: "light4", hex: "#a89984" },
			{ name: "gray", hex: "#928374" },
			{ name: "dark0_hard", hex: "#1d2021" },
			{ name: "dark0", hex: "#282828" },
			{ name: "dark0_soft", hex: "#32302f" },
			{ name: "dark1", hex: "#3c3836" },
			{ name: "dark2", hex: "#504945" },
			{ name: "dark3", hex: "#665c54" },
			{ name: "dark4", hex: "#7c6f64" },
			{ name: "neutral_red", hex: "#cc241d" },
			{ name: "neutral_green", hex: "#98971a" },
			{ name: "neutral_yellow", hex: "#d79921" },
			{ name: "neutral_blue", hex: "#458588" },
			{ name: "neutral_purple", hex: "#b16286" },
			{ name: "neutral_aqua", hex: "#689d6a" },
			{ name: "neutral_orange", hex: "#d65d0e" },
			{ name: "faded_red", hex: "#9d0006" },
			{ name: "faded_green", hex: "#79740e" },
			{ name: "faded_yellow", hex: "#b57614" },
			{ name: "faded_blue", hex: "#076678" },
			{ name: "faded_purple", hex: "#8f3f71" },
			{ name: "faded_aqua", hex: "#427b58" },
			{ name: "faded_orange", hex: "#af3a03" },
			],
		},
		{
			name: "Medium Light",
			appearance: "light",
			source: "https://github.com/morhetz/gruvbox",
			colors: [
			{ name: "light0", hex: "#fbf1c7" },
			{ name: "light1", hex: "#ebdbb2" },
			{ name: "light2", hex: "#d5c4a1" },
			{ name: "light3", hex: "#bdae93" },
			{ name: "light4", hex: "#a89984" },
			{ name: "gray", hex: "#928374" },
			{ name: "dark0_hard", hex: "#1d2021" },
			{ name: "dark0", hex: "#282828" },
			{ name: "dark0_soft", hex: "#32302f" },
			{ name: "dark1", hex: "#3c3836" },
			{ name: "dark2", hex: "#504945" },
			{ name: "dark3", hex: "#665c54" },
			{ name: "dark4", hex: "#7c6f64" },
			{ name: "neutral_red", hex: "#cc241d" },
			{ name: "neutral_green", hex: "#98971a" },
			{ name: "neutral_yellow", hex: "#d79921" },
			{ name: "neutral_blue", hex: "#458588" },
			{ name: "neutral_purple", hex: "#b16286" },
			{ name: "neutral_aqua", hex: "#689d6a" },
			{ name: "neutral_orange", hex: "#d65d0e" },
			{ name: "faded_red", hex: "#9d0006" },
			{ name: "faded_green", hex: "#79740e" },
			{ name: "faded_yellow", hex: "#b57614" },
			{ name: "faded_blue", hex: "#076678" },
			{ name: "faded_purple", hex: "#8f3f71" },
			{ name: "faded_aqua", hex: "#427b58" },
			{ name: "faded_orange", hex: "#af3a03" },
			],
		},
		{
			name: "Soft Light",
			appearance: "light",
			source: "https://github.com/morhetz/gruvbox",
			colors: [
			{ name: "light0_soft", hex: "#f2e5bc" },
			{ name: "light1", hex: "#ebdbb2" },
			{ name: "light2", hex: "#d5c4a1" },
			{ name: "light3", hex: "#bdae93" },
			{ name: "light4", hex: "#a89984" },
			{ name: "gray", hex: "#928374" },
			{ name: "dark0_hard", hex: "#1d2021" },
			{ name: "dark0", hex: "#282828" },
			{ name: "dark0_soft", hex: "#32302f" },
			{ name: "dark1", hex: "#3c3836" },
			{ name: "dark2", hex: "#504945" },
			{ name: "dark3", hex: "#665c54" },
			{ name: "dark4", hex: "#7c6f64" },
			{ name: "neutral_red", hex: "#cc241d" },
			{ name: "neutral_green", hex: "#98971a" },
			{ name: "neutral_yellow", hex: "#d79921" },
			{ name: "neutral_blue", hex: "#458588" },
			{ name: "neutral_purple", hex: "#b16286" },
			{ name: "neutral_aqua", hex: "#689d6a" },
			{ name: "neutral_orange", hex: "#d65d0e" },
			{ name: "faded_red", hex: "#9d0006" },
			{ name: "faded_green", hex: "#79740e" },
			{ name: "faded_yellow", hex: "#b57614" },
			{ name: "faded_blue", hex: "#076678" },
			{ name: "faded_purple", hex: "#8f3f71" },
			{ name: "faded_aqua", hex: "#427b58" },
			{ name: "faded_orange", hex: "#af3a03" },
			],
		},
		{
			name: "Hard Dark",
			appearance: "dark",
			source: "https://github.com/morhetz/gruvbox",
			colors: [
			{ name: "dark0_hard", hex: "#1d2021" },
			{ name: "dark1", hex: "#3c3836" },
			{ name: "dark2", hex: "#504945" },
			{ name: "dark3", hex: "#665c54" },
			{ name: "dark4", hex: "#7c6f64" },
			{ name: "gray", hex: "#928374" },
			{ name: "light0_hard", hex: "#f9f5d7" },
			{ name: "light0", hex: "#fbf1c7" },
			{ name: "light0_soft", hex: "#f2e5bc" },
			{ name: "light1", hex: "#ebdbb2" },
			{ name: "light2", hex: "#d5c4a1" },
			{ name: "light3", hex: "#bdae93" },
			{ name: "light4", hex: "#a89984" },
			{ name: "bright_red", hex: "#fb4934" },
			{ name: "bright_green", hex: "#b8bb26" },
			{ name: "bright_yellow", hex: "#fabd2f" },
			{ name: "bright_blue", hex: "#83a598" },
			{ name: "bright_purple", hex: "#d3869b" },
			{ name: "bright_aqua", hex: "#8ec07c" },
			{ name: "bright_orange", hex: "#fe8019" },
			{ name: "neutral_red", hex: "#cc241d" },
			{ name: "neutral_green", hex: "#98971a" },
			{ name: "neutral_yellow", hex: "#d79921" },
			{ name: "neutral_blue", hex: "#458588" },
			{ name: "neutral_purple", hex: "#b16286" },
			{ name: "neutral_aqua", hex: "#689d6a" },
			{ name: "neutral_orange", hex: "#d65d0e" },
			],
		},
		{
			name: "Medium Dark",
			appearance: "dark",
			source: "https://github.com/morhetz/gruvbox",
			colors: [
			{ name: "dark0", hex: "#282828" },
			{ name: "dark1", hex: "#3c3836" },
			{ name: "dark2", hex: "#504945" },
			{ name: "dark3", hex: "#665c54" },
			{ name: "dark4", hex: "#7c6f64" },
			{ name: "gray", hex: "#928374" },
			{ name: "light0_hard", hex: "#f9f5d7" },
			{ name: "light0", hex: "#fbf1c7" },
			{ name: "light0_soft", hex: "#f2e5bc" },
			{ name: "light1", hex: "#ebdbb2" },
			{ name: "light2", hex: "#d5c4a1" },
			{ name: "light3", hex: "#bdae93" },
			{ name: "light4", hex: "#a89984" },
			{ name: "bright_red", hex: "#fb4934" },
			{ name: "bright_green", hex: "#b8bb26" },
			{ name: "bright_yellow", hex: "#fabd2f" },
			{ name: "bright_blue", hex: "#83a598" },
			{ name: "bright_purple", hex: "#d3869b" },
			{ name: "bright_aqua", hex: "#8ec07c" },
			{ name: "bright_orange", hex: "#fe8019" },
			{ name: "neutral_red", hex: "#cc241d" },
			{ name: "neutral_green", hex: "#98971a" },
			{ name: "neutral_yellow", hex: "#d79921" },
			{ name: "neutral_blue", hex: "#458588" },
			{ name: "neutral_purple", hex: "#b16286" },
			{ name: "neutral_aqua", hex: "#689d6a" },
			{ name: "neutral_orange", hex: "#d65d0e" },
			],
		},
		{
			name: "Soft Dark",
			appearance: "dark",
			source: "https://github.com/morhetz/gruvbox",
			colors: [
			{ name: "dark0_soft", hex: "#32302f" },
			{ name: "dark1", hex: "#3c3836" },
			{ name: "dark2", hex: "#504945" },
			{ name: "dark3", hex: "#665c54" },
			{ name: "dark4", hex: "#7c6f64" },
			{ name: "gray", hex: "#928374" },
			{ name: "light0_hard", hex: "#f9f5d7" },
			{ name: "light0", hex: "#fbf1c7" },
			{ name: "light0_soft", hex: "#f2e5bc" },
			{ name: "light1", hex: "#ebdbb2" },
			{ name: "light2", hex: "#d5c4a1" },
			{ name: "light3", hex: "#bdae93" },
			{ name: "light4", hex: "#a89984" },
			{ name: "bright_red", hex: "#fb4934" },
			{ name: "bright_green", hex: "#b8bb26" },
			{ name: "bright_yellow", hex: "#fabd2f" },
			{ name: "bright_blue", hex: "#83a598" },
			{ name: "bright_purple", hex: "#d3869b" },
			{ name: "bright_aqua", hex: "#8ec07c" },
			{ name: "bright_orange", hex: "#fe8019" },
			{ name: "neutral_red", hex: "#cc241d" },
			{ name: "neutral_green", hex: "#98971a" },
			{ name: "neutral_yellow", hex: "#d79921" },
			{ name: "neutral_blue", hex: "#458588" },
			{ name: "neutral_purple", hex: "#b16286" },
			{ name: "neutral_aqua", hex: "#689d6a" },
			{ name: "neutral_orange", hex: "#d65d0e" },
			],
		},
	],
	Nord: [
		{
			name: "Nord",
			appearance: "dark",
			source: "https://www.nordtheme.com/docs/colors-and-palettes",
			colors: [
			{ name: "Polar Night (nord0)", hex: "#2e3440" },
			{ name: "Polar Night (nord1)", hex: "#3b4252" },
			{ name: "Polar Night (nord2)", hex: "#434c5e" },
			{ name: "Polar Night (nord3)", hex: "#4c566a" },
			{ name: "Snow Storm (nord4)", hex: "#d8dee9" },
			{ name: "Snow Storm (nord5)", hex: "#e5e9f0" },
			{ name: "Snow Storm (nord6)", hex: "#eceff4" },
			{ name: "Frost (nord7)", hex: "#8fbcbb" },
			{ name: "Frost (nord8)", hex: "#88c0d0" },
			{ name: "Frost (nord9)", hex: "#81a1c1" },
			{ name: "Frost (nord10)", hex: "#5e81ac" },
			{ name: "Aurora (nord11)", hex: "#bf616a" },
			{ name: "Aurora (nord12)", hex: "#d08770" },
			{ name: "Aurora (nord13)", hex: "#ebcb8b" },
			{ name: "Aurora (nord14)", hex: "#a3be8c" },
			{ name: "Aurora (nord15)", hex: "#b48ead" },
			],
		},
	],
	"Rosé Pine": [
		{
			name: "Main",
			appearance: "dark",
			source: "https://github.com/rose-pine/rose-pine",
			colors: [
			{ name: "Base", hex: "#191724" },
			{ name: "Surface", hex: "#1f1d2e" },
			{ name: "Overlay", hex: "#26233a" },
			{ name: "Muted", hex: "#6e6a86" },
			{ name: "Subtle", hex: "#908caa" },
			{ name: "Text", hex: "#e0def4" },
			{ name: "Love", hex: "#eb6f92" },
			{ name: "Gold", hex: "#f6c177" },
			{ name: "Rose", hex: "#ebbcba" },
			{ name: "Pine", hex: "#31748f" },
			{ name: "Foam", hex: "#9ccfd8" },
			{ name: "Iris", hex: "#c4a7e7" },
			],
		},
		{
			name: "Moon",
			appearance: "dark",
			source: "https://github.com/rose-pine/rose-pine",
			colors: [
			{ name: "Base", hex: "#232136" },
			{ name: "Surface", hex: "#2a273f" },
			{ name: "Overlay", hex: "#393552" },
			{ name: "Muted", hex: "#6e6a86" },
			{ name: "Subtle", hex: "#908caa" },
			{ name: "Text", hex: "#e0def4" },
			{ name: "Love", hex: "#eb6f92" },
			{ name: "Gold", hex: "#f6c177" },
			{ name: "Rose", hex: "#ea9a97" },
			{ name: "Pine", hex: "#3e8fb0" },
			{ name: "Foam", hex: "#9ccfd8" },
			{ name: "Iris", hex: "#c4a7e7" },
			],
		},
		{
			name: "Dawn",
			appearance: "light",
			source: "https://github.com/rose-pine/rose-pine",
			colors: [
			{ name: "Base", hex: "#faf4ed" },
			{ name: "Surface", hex: "#fffaf3" },
			{ name: "Overlay", hex: "#f2e9e1" },
			{ name: "Muted", hex: "#9893a5" },
			{ name: "Subtle", hex: "#797593" },
			{ name: "Text", hex: "#575279" },
			{ name: "Love", hex: "#b4637a" },
			{ name: "Gold", hex: "#ea9d34" },
			{ name: "Rose", hex: "#d7827e" },
			{ name: "Pine", hex: "#286983" },
			{ name: "Foam", hex: "#56949f" },
			{ name: "Iris", hex: "#907aa9" },
			],
		},
	],
	Solarized: [
		{
			name: "Light",
			appearance: "light",
			source: "https://ethanschoonover.com/solarized",
			colors: [
			{ name: "base03", hex: "#002b36" },
			{ name: "base02", hex: "#073642" },
			{ name: "base01", hex: "#586e75" },
			{ name: "base00", hex: "#657b83" },
			{ name: "base0", hex: "#839496" },
			{ name: "base1", hex: "#93a1a1" },
			{ name: "base2", hex: "#eee8d5" },
			{ name: "base3", hex: "#fdf6e3" },
			{ name: "yellow", hex: "#b58900" },
			{ name: "orange", hex: "#cb4b16" },
			{ name: "red", hex: "#dc322f" },
			{ name: "magenta", hex: "#d33682" },
			{ name: "violet", hex: "#6c71c4" },
			{ name: "blue", hex: "#268bd2" },
			{ name: "cyan", hex: "#2aa198" },
			{ name: "green", hex: "#859900" },
			],
		},
		{
			name: "Dark",
			appearance: "dark",
			source: "https://ethanschoonover.com/solarized",
			colors: [
			{ name: "base03", hex: "#002b36" },
			{ name: "base02", hex: "#073642" },
			{ name: "base01", hex: "#586e75" },
			{ name: "base00", hex: "#657b83" },
			{ name: "base0", hex: "#839496" },
			{ name: "base1", hex: "#93a1a1" },
			{ name: "base2", hex: "#eee8d5" },
			{ name: "base3", hex: "#fdf6e3" },
			{ name: "yellow", hex: "#b58900" },
			{ name: "orange", hex: "#cb4b16" },
			{ name: "red", hex: "#dc322f" },
			{ name: "magenta", hex: "#d33682" },
			{ name: "violet", hex: "#6c71c4" },
			{ name: "blue", hex: "#268bd2" },
			{ name: "cyan", hex: "#2aa198" },
			{ name: "green", hex: "#859900" },
			],
		},
	],
};

function normalizePresetName(paletteName: string): PresetPaletteName | null {
	if (paletteName === "Rose Pine") return "Rosé Pine";
	if (paletteName in COLOR_PALETTES) return paletteName as PresetPaletteName;
	return null;
}

/** Theme default when a stored variant is missing or stale: first dark appearance, else first entry. */
function defaultVariant(variants: PaletteVariant[]): PaletteVariant {
	return variants.find((v) => v.appearance === "dark") ?? variants[0];
}

/**
 * Appearance-aware default for settings UX when the user picks a new theme.
 * Prefers a variant matching Obsidian's current light/dark, else first dark, else first.
 */
export function defaultVariantName(variants: PaletteVariant[], appearance: PaletteMode): string {
	const match = variants.find((v) => v.appearance === appearance);
	if (match) return match.name;
	return defaultVariant(variants).name;
}

/** Resolves which named variant to use for a preset (stale-value fallback lives only here). */
export function resolvePaletteVariant(
	paletteName: PaletteName,
	variantName: string | undefined,
): PaletteVariant | null {
	const preset = normalizePresetName(paletteName);
	if (!preset) return null;
	const variants = COLOR_PALETTES[preset];
	if (!variants.length) return null;
	if (variantName) {
		const found = variants.find((v) => v.name === variantName);
		if (found) return found;
	}
	return defaultVariant(variants);
}

/** Resolves the colour list to show in the picker for the plugin's current palette selection. */
export function resolvePaletteColors(
	paletteName: PaletteName,
	variantName: string | undefined,
	customPaletteColors: PaletteColor[],
): PaletteColor[] {
	if (paletteName === "Custom") return customPaletteColors;
	const variant = resolvePaletteVariant(paletteName, variantName);
	return variant ? variant.colors : [];
}
