import {
	ICON_ADD_CIRCLE,
	ICON_ADD_SQUARE,
	ICON_ARCHIVE,
	ICON_ARCHIVE_FILLED,
	ICON_AXE,
	ICON_BLOCKQUOTE,
	ICON_BOOK_DUOTONE,
	ICON_BOOK_OPEN,
	ICON_BOOK_OPEN_FILLED,
	ICON_BOOK_PLUS,
	ICON_BOOK_SPINE,
	ICON_BOOKMARK,
	ICON_BOOKMARK_DUOTONE,
	ICON_BOOKMARK_FILL,
	ICON_BOOKSHELF,
	ICON_BOWL,
	ICON_BOWL_RICE,
	ICON_BUILDING_A,
	ICON_BUILDING_B,
	ICON_BUILDING_C,
	ICON_CALENDAR,
	ICON_CALENDAR_EVENT,
	ICON_CALENDAR_PLAIN,
	ICON_CALENDAR_WEEK,
	ICON_CARDS,
	ICON_CASTLE,
	ICON_CHECK_CIRCLE,
	ICON_CHECK_CIRCLE_FILL,
	ICON_CHEVRON_DOWN,
	ICON_CHEVRON_RIGHT,
	ICON_CITY,
	ICON_CLIPBOARD_ADD_DUOTONE,
	ICON_CLIPBOARD_DUOTONE,
	ICON_CLIPBOARD_LIST_DUOTONE,
	ICON_CLIPBOARD_TEXT_DUOTONE,
	ICON_CODEX,
	ICON_CONTINUOUS_MODE,
	ICON_CROWN,
	ICON_CYCLE_ALT,
	ICON_DASHBOARD_CHART,
	ICON_DEAD_TREE,
	ICON_DOCUMENT_PAGE_BREAK,
	ICON_DOSSIER,
	ICON_DRAGON,
	ICON_EDIT_PEN,
	ICON_EGG,
	ICON_EXCHANGE,
	ICON_EXCLAMATION_SQUARE,
	ICON_EXCLAMATION_SQUARE_FILL,
	ICON_EXPLOSION,
	ICON_EYE,
	ICON_EYE_DUOTONE,
	ICON_EYE_OUTLINE,
	ICON_FILE_PLUS,
	ICON_FILE_TEXT_DUOTONE,
	ICON_FILTER,
	ICON_FILTER_LIST,
	ICON_FIRE,
	ICON_FIREWORKS,
	ICON_FISH,
	ICON_FLAG,
	ICON_FLAG_FILL,
	ICON_FOLDER,
	ICON_FOLDER_PLUS,
	ICON_FOREST,
	ICON_FORGE,
	ICON_GALAXY_FILL,
	ICON_GALAXY_OUTLINE,
	ICON_GEARS,
	ICON_HASHTAG_SQUARE_DUOTONE,
	ICON_HEART_CIRCLE,
	ICON_HEART_CIRCLE_FILL,
	ICON_HEART_FILL,
	ICON_HEART_OUTLINE,
	ICON_INFO_CIRCLE,
	ICON_LAYOUT_SELECTOR,
	ICON_LIGHTNING,
	ICON_LINK2,
	ICON_LINK2_DUOTONE,
	ICON_LIST3_FILLED,
	ICON_LOCATION_TARGET_SQUARE,
	ICON_LOCK,
	ICON_MAGIC_WAND,
	ICON_MAP_PIN,
	ICON_MAP_PIN_PLUS,
	ICON_MESSAGE,
	ICON_MOUNTAIN,
	ICON_MULTIPLY_SQUARE,
	ICON_MUSIC_NOTE,
	ICON_NOTEBOOK,
	ICON_NOTEBOOK_DUOTONE,
	ICON_OBSIDIAN,
	ICON_PAGE_PORTRAIT,
	ICON_PAGE_TEXT,
	ICON_NUMBER_CIRCLE_0,
	ICON_NUMBER_CIRCLE_1,
	ICON_NUMBER_CIRCLE_2,
	ICON_NUMBER_CIRCLE_3,
	ICON_NUMBER_CIRCLE_4,
	ICON_NUMBER_CIRCLE_5,
	ICON_NUMBER_CIRCLE_6,
	ICON_NUMBER_CIRCLE_7,
	ICON_NUMBER_CIRCLE_8,
	ICON_NUMBER_CIRCLE_9,
	ICON_PAW,
	ICON_PAW_ROUNDED,
	ICON_PERSON_2_FILL,
	ICON_PERSON_3_FILL,
	ICON_PERSON_FILL,
	ICON_PERSON_FILL_ADD,
	ICON_PINE_TREE,
	ICON_PLANE,
	ICON_PLANET,
	ICON_PLUS_SQUARE,
	ICON_MINUS_SQUARE,
	ICON_MINUS_CIRCLE_DUOTONE,
	ICON_CHECK_SQUARE,
	ICON_PLOT_THREADS,
	ICON_RAIN,
	ICON_REFRESH_SQUARE,
	ICON_RIVER,
	ICON_ROAD,
	ICON_ROCKETSHIP,
	ICON_SCROLL,
	ICON_SERIES,
	ICON_SETTINGS_GEAR,
	ICON_SHIELD,
	ICON_SHIP,
	ICON_SHOP,
	ICON_SKULL,
	ICON_SNOW,
	ICON_SPARKLES,
	ICON_SPEECH_BUBBLE,
	ICON_STAR_DUOTONE,
	ICON_STAR_FILL,
	ICON_STAR_OUTLINE,
	ICON_STARS_FILL,
	ICON_STARS_TRIO,
	ICON_STORYTELLING,
	ICON_SUN_FILL,
	ICON_SWORD,
	ICON_SWORDS_CROSSED,
	ICON_TAG,
	ICON_TAG_DUOTONE,
	ICON_TAG_EDIT,
	ICON_TARGET_DUOTONE,
	ICON_TEMPLE,
	ICON_TEXT_HEADER_1,
	ICON_TEXT_HEADER_2,
	ICON_TEXT_HEADER_3,
	ICON_TEXT_HEADER_4,
	ICON_TEXT_HEADER_4_CARET,
	ICON_TEXT_HEADER_5,
	ICON_TEXT_HEADER_6,
	ICON_THUNDERSTORM,
	ICON_TIMELINE,
	ICON_TOOLS,
	ICON_TOWER_BLOCK,
	ICON_TOWER_FORTRESS,
	ICON_TOWER_SLIM,
	ICON_TRANSPORT_NEXT,
	ICON_TRANSPORT_PREVIOUS,
	ICON_TRANSPORT_TO_END,
	ICON_TRANSPORT_TO_START,
	ICON_TREE,
	ICON_TRUCK,
	ICON_UNARCHIVE,
	ICON_UNICORN,
	ICON_UNPLACED,
	ICON_VERIFIED_CHECK,
	ICON_VERIFIED_CHECK_FILL,
	ICON_VERTICAL_SCROLL_POINT,
	ICON_X,
} from "./icons";

/** One entry in a fixed, programmer-curated icon catalog. Not user-extensible — end users pick
 * from these lists (via IconPickerModal) but never add to them; only a code change (adding an
 * entry here, plus a corresponding icon in icons.ts) grows a catalog. */
export interface IconCatalogEntry {
	alias: string;
	label: string;
	iconId: string;
}

/**
 * Icon choices for Codex types (Person/Place/Populace, and anything a user adds alongside them —
 * including nested types under Person/Place, see TagDefinition.parentId). Themed around "kinds of
 * things a story world has": people, places, roles, institutions, transport, geography,
 * conflict/magic (the last two chosen with nested types like Hero/Villain in mind), weather,
 * food, and creatures/mythical beings.
 */
export const CODEX_ICON_CATALOG: IconCatalogEntry[] = [
	{ alias: "person-fill", label: "Person", iconId: ICON_PERSON_FILL },
	{ alias: "location-pin", label: "Location pin", iconId: ICON_MAP_PIN },
	{ alias: "person-2-fill", label: "Two people", iconId: ICON_PERSON_2_FILL },
	{ alias: "stars", label: "Stars", iconId: ICON_STARS_FILL },
	{ alias: "shop", label: "Shop", iconId: ICON_SHOP },
	{ alias: "settings-gear", label: "Gear", iconId: ICON_SETTINGS_GEAR },
	{ alias: "fire", label: "Fire", iconId: ICON_FIRE },
	{ alias: "earth", label: "Earth", iconId: ICON_CODEX },
	{ alias: "crown", label: "Crown", iconId: ICON_CROWN },
	{ alias: "calendar-plain", label: "Calendar", iconId: ICON_CALENDAR_PLAIN },
	{ alias: "calendar-dotted", label: "Calendar (dated)", iconId: ICON_CALENDAR },
	{ alias: "building-a", label: "Building", iconId: ICON_BUILDING_A },
	{ alias: "building-b", label: "Building (tall)", iconId: ICON_BUILDING_B },
	{ alias: "bookmark", label: "Bookmark", iconId: ICON_BOOKMARK },
	{ alias: "bookmark-fill", label: "Bookmark (filled)", iconId: ICON_BOOKMARK_FILL },
	{ alias: "truck", label: "Truck", iconId: ICON_TRUCK },
	{ alias: "rocketship", label: "Rocketship", iconId: ICON_ROCKETSHIP },
	{ alias: "plane", label: "Plane", iconId: ICON_PLANE },
	{ alias: "ship", label: "Ship", iconId: ICON_SHIP },
	{ alias: "road", label: "Road", iconId: ICON_ROAD },
	{ alias: "mountain", label: "Mountain", iconId: ICON_MOUNTAIN },
	{ alias: "tower-block", label: "Tower (block)", iconId: ICON_TOWER_BLOCK },
	{ alias: "tower-slim", label: "Tower (slim)", iconId: ICON_TOWER_SLIM },
	{ alias: "tower-fortress", label: "Tower (fortress)", iconId: ICON_TOWER_FORTRESS },
	{ alias: "shield", label: "Shield", iconId: ICON_SHIELD },
	{ alias: "gears", label: "Gears", iconId: ICON_GEARS },
	{ alias: "explosion", label: "Explosion", iconId: ICON_EXPLOSION },
	{ alias: "swords-crossed", label: "Swords (crossed)", iconId: ICON_SWORDS_CROSSED },
	{ alias: "sword", label: "Sword", iconId: ICON_SWORD },
	{ alias: "axe", label: "Axe", iconId: ICON_AXE },
	{ alias: "magic-wand", label: "Magic wand", iconId: ICON_MAGIC_WAND },
	{ alias: "sun-fill", label: "Sun", iconId: ICON_SUN_FILL },
	{ alias: "thunderstorm", label: "Thunderstorm", iconId: ICON_THUNDERSTORM },
	{ alias: "snow", label: "Snow", iconId: ICON_SNOW },
	{ alias: "rain", label: "Rain", iconId: ICON_RAIN },
	{ alias: "river", label: "River", iconId: ICON_RIVER },
	{ alias: "dead-tree", label: "Dead tree", iconId: ICON_DEAD_TREE },
	{ alias: "pine-tree", label: "Pine tree", iconId: ICON_PINE_TREE },
	{ alias: "tree", label: "Tree", iconId: ICON_TREE },
	{ alias: "bowl-rice", label: "Bowl of rice", iconId: ICON_BOWL_RICE },
	{ alias: "bowl", label: "Bowl", iconId: ICON_BOWL },
	{ alias: "egg", label: "Egg", iconId: ICON_EGG },
	{ alias: "dragon", label: "Dragon", iconId: ICON_DRAGON },
	{ alias: "unicorn", label: "Unicorn", iconId: ICON_UNICORN },
	{ alias: "fish", label: "Fish", iconId: ICON_FISH },
	{ alias: "paw", label: "Paw print", iconId: ICON_PAW },
	{ alias: "skull", label: "Skull", iconId: ICON_SKULL },
	{ alias: "music-note", label: "Music note", iconId: ICON_MUSIC_NOTE },
	{ alias: "speech-bubble", label: "Speech bubble", iconId: ICON_SPEECH_BUBBLE },
	{ alias: "scroll", label: "Scroll", iconId: ICON_SCROLL },
	{ alias: "sparkles", label: "Sparkles", iconId: ICON_SPARKLES },
	{ alias: "stars-trio", label: "Stars (trio)", iconId: ICON_STARS_TRIO },
	{ alias: "person-3-fill", label: "Three people", iconId: ICON_PERSON_3_FILL },
	{ alias: "paw-rounded", label: "Paw print (rounded)", iconId: ICON_PAW_ROUNDED },
	{ alias: "city", label: "City", iconId: ICON_CITY },
	{ alias: "fireworks", label: "Fireworks", iconId: ICON_FIREWORKS },
	{ alias: "galaxy-outline", label: "Galaxy (outline)", iconId: ICON_GALAXY_OUTLINE },
	{ alias: "galaxy-fill", label: "Galaxy (filled)", iconId: ICON_GALAXY_FILL },
	{ alias: "forest", label: "Forest", iconId: ICON_FOREST },
	{ alias: "castle", label: "Castle", iconId: ICON_CASTLE },
	{ alias: "planet", label: "Planet", iconId: ICON_PLANET },
	{ alias: "temple", label: "Temple", iconId: ICON_TEMPLE },
	{ alias: "lightning", label: "Lightning", iconId: ICON_LIGHTNING },
	{ alias: "building-c", label: "Building (outline)", iconId: ICON_BUILDING_C },
];

/**
 * Icon choices for chapter tags and novel tags — a shared pool, themed around editing/review
 * status: reference/status (done, done-fill, circle-tick, circle-tick-fill, info), progress
 * (number-0 through number-9 — handy for "editing pass N"-style tags), reaction (heart-circle,
 * heart-circle-fill, heart-outline, heart-fill), editing (pencil), priority (star, star-duotone,
 * star-fill), marking (bookmark, bookmark-fill), flags (flag, flag-fill), and warnings
 * (warning-square, warning-square-fill). Order here is also IconPickerModal's display order for
 * this list, chosen deliberately (see the modal's own doc comment) — eye-watching, message, and
 * lock don't fit any of those groups cleanly and sit at the end. Exactly 32 entries, an 8x4 grid
 * in the picker.
 *
 * Every entry here is a custom SVG (see src/icons.ts) — no stock Lucide icons remain in this
 * catalog as of the circle-tick/flag/star/lock replacements.
 */
export const TAG_ICON_CATALOG: IconCatalogEntry[] = [
	{ alias: "done", label: "Done", iconId: ICON_VERIFIED_CHECK },
	{ alias: "done-fill", label: "Done (filled)", iconId: ICON_VERIFIED_CHECK_FILL },
	{ alias: "circle-tick", label: "Circle tick", iconId: ICON_CHECK_CIRCLE },
	{ alias: "circle-tick-fill", label: "Circle tick (filled)", iconId: ICON_CHECK_CIRCLE_FILL },
	{ alias: "info", label: "Info", iconId: ICON_INFO_CIRCLE },
	{ alias: "number-0", label: "Number 0", iconId: ICON_NUMBER_CIRCLE_0 },
	{ alias: "number-1", label: "Number 1", iconId: ICON_NUMBER_CIRCLE_1 },
	{ alias: "number-2", label: "Number 2", iconId: ICON_NUMBER_CIRCLE_2 },
	{ alias: "number-3", label: "Number 3", iconId: ICON_NUMBER_CIRCLE_3 },
	{ alias: "number-4", label: "Number 4", iconId: ICON_NUMBER_CIRCLE_4 },
	{ alias: "number-5", label: "Number 5", iconId: ICON_NUMBER_CIRCLE_5 },
	{ alias: "number-6", label: "Number 6", iconId: ICON_NUMBER_CIRCLE_6 },
	{ alias: "number-7", label: "Number 7", iconId: ICON_NUMBER_CIRCLE_7 },
	{ alias: "number-8", label: "Number 8", iconId: ICON_NUMBER_CIRCLE_8 },
	{ alias: "number-9", label: "Number 9", iconId: ICON_NUMBER_CIRCLE_9 },
	{ alias: "heart-circle", label: "Heart circle", iconId: ICON_HEART_CIRCLE },
	{ alias: "heart-circle-fill", label: "Heart circle (filled)", iconId: ICON_HEART_CIRCLE_FILL },
	{ alias: "heart-outline", label: "Heart (outline)", iconId: ICON_HEART_OUTLINE },
	{ alias: "heart-fill", label: "Heart (filled)", iconId: ICON_HEART_FILL },
	{ alias: "pencil", label: "Pencil", iconId: ICON_EDIT_PEN },
	{ alias: "star", label: "Star", iconId: ICON_STAR_OUTLINE },
	{ alias: "star-duotone", label: "Star (duotone)", iconId: ICON_STAR_DUOTONE },
	{ alias: "star-fill", label: "Star (filled)", iconId: ICON_STAR_FILL },
	{ alias: "bookmark", label: "Bookmark", iconId: ICON_BOOKMARK },
	{ alias: "bookmark-fill", label: "Bookmark (filled)", iconId: ICON_BOOKMARK_FILL },
	{ alias: "flag", label: "Flag", iconId: ICON_FLAG },
	{ alias: "flag-fill", label: "Flag (filled)", iconId: ICON_FLAG_FILL },
	{ alias: "warning-square", label: "Warning (square)", iconId: ICON_EXCLAMATION_SQUARE },
	{ alias: "warning-square-fill", label: "Warning (filled square)", iconId: ICON_EXCLAMATION_SQUARE_FILL },
	{ alias: "eye-watching", label: "Eye", iconId: ICON_EYE_OUTLINE },
	{ alias: "message", label: "Message", iconId: ICON_MESSAGE },
	{ alias: "lock", label: "Lock", iconId: ICON_LOCK },
];

/** Tag-catalog aliases offered on vault `#tag`s in addition to every Codex type icon. `bookmark-fill`
 * is already in CODEX_ICON_CATALOG — listed here so the picker spec stays explicit, then dropped
 * when building VAULT_TAG_ICON_CATALOG so the grid never shows the same alias twice. */
const VAULT_TAG_EXTRA_ALIASES: readonly string[] = [
	"number-0",
	"number-1",
	"number-2",
	"number-3",
	"number-4",
	"number-5",
	"number-6",
	"number-7",
	"number-8",
	"number-9",
	"heart-fill",
	"star-duotone",
	"star-fill",
	"bookmark-fill",
	"flag-fill",
	"warning-square-fill",
];

/** Icon choices for vault `#tag`s: the full Codex type catalog, then the status/marking extras
 * from TAG_ICON_CATALOG that types don't already offer. Order is types-first, then extras in
 * TAG_ICON_CATALOG's own order. */
export const VAULT_TAG_ICON_CATALOG: IconCatalogEntry[] = [
	...CODEX_ICON_CATALOG,
	...TAG_ICON_CATALOG.filter(
		(entry) =>
			VAULT_TAG_EXTRA_ALIASES.includes(entry.alias) &&
			!CODEX_ICON_CATALOG.some((codexEntry) => codexEntry.alias === entry.alias),
	),
];

export interface IconRegistryEntry {
	id: string;
	label: string;
	source: "custom" | "lucide";
	/** Where this icon is currently wired up, as "File.ts — what it is". Empty means nothing in the app renders it. */
	usedIn: string[];
}

/**
 * Standing rule for any icon shown alongside others at a shared, uniform CSS box size (a transport
 * row, an icon-picker grid, anything with a "these should all look the same size" expectation):
 * match the *painted fraction of the viewBox*, not the viewBox's own size. Two icons can share an
 * identical `width`/`height` box and still read as mismatched if one artwork is inset within its
 * own viewBox (a ring with a gap to the edge) and the other runs edge-to-edge. The transport
 * chevrons and ICON_CONTINUOUS_MODE's carousel are inset 24×24 ReIcon artwork; padding a fuller
 * glyph's box in icons.ts to match that painted fraction is the actual fix — not a per-button
 * forced pixel size in JS.
 */

/**
 * Hand-maintained inventory of every icon storyForge renders, custom or stock.
 * There's no way to determine "used or not" by inspecting the compiled plugin
 * at runtime, so this list is the source of truth — update it whenever an
 * icon is added, removed, or rewired to a different spot in the UI.
 */
export const ICON_REGISTRY: IconRegistryEntry[] = [
	// Custom (registered via addIcon in icons.ts)
	{ id: ICON_UNPLACED, label: "Unplaced", source: "custom", usedIn: ["TopPanel.ts — Unplaced section header (books & chapters)"] },
	{
		id: ICON_ARCHIVE,
		label: "Archive (line box)",
		source: "custom",
		usedIn: [
			"StoryContextView.ts — Archive tab (Novel/Chapter/Details/Dossier row)",
			"UiFormattingModal.ts / uiStylePreviewSample.ts — story-context archive formatting leaf and preview",
			"ArchiveView.ts — legacy Archive leaf header (detached from rail)",
		],
	},
	{
		id: ICON_UNARCHIVE,
		label: "Unarchive",
		source: "custom",
		usedIn: ["archivePanel.ts — unarchive row button"],
	},
	{ id: ICON_CODEX, label: "Codex", source: "custom", usedIn: ["StoryForgeView.ts — layout tab row, leading icon on the \"Codex\" tab", "archivePanel.ts — Archive Codex-mode icon", "StoryContextView.ts — Notebook pane Codex-index switcher", "TagRegistryModal.ts — types manager Codex tab", "iconRegistry.ts — Codex icon catalog (\"earth\")"] },
	{
		id: ICON_SERIES,
		label: "Series",
		source: "custom",
		usedIn: [
			"StoryForgeView.ts — storyforge-face tab icon; also the layout tab row's \"Series\" tab icon",
			"SeriesOverviewView.ts — view tab icon",
		],
	},
	{
		id: ICON_FILTER,
		label: "Settings",
		source: "custom",
		usedIn: [
			"TopPanel.ts — series-mode settings button (opens SeriesModal; Series layout only)",
			"uiStylePreviewSample.ts — settings-tab live style preview mockup",
		],
	},
	{
		id: ICON_FILTER_LIST,
		label: "Filter list",
		source: "custom",
		usedIn: ["BottomPanel.ts — Codex tree type-filter button"],
	},
	{
		id: ICON_TIMELINE,
		label: "Synopsis and plot",
		source: "custom",
		usedIn: [
			"TopPanel.ts — book synopsis/plot settings button",
			"BookSynopsisModal.ts — \"Plot\" section header line",
			"SeriesOverviewView.ts — \"Plot\" section header line",
		],
	},
	{
		id: ICON_BOOK_PLUS,
		label: "New book",
		source: "custom",
		usedIn: ["SeriesModal.ts — add book button"],
	},
	{
		id: ICON_BOOK_OPEN,
		label: "Open book",
		source: "custom",
		usedIn: [
			"TopPanel.ts — Series tab's book list, marks the currently open/selected novel",
			"StoryForgeView.ts — storytelling-mode tab icon",
		],
	},
	{
		id: ICON_BOOK_SPINE,
		label: "Book (spine)",
		source: "custom",
		usedIn: [],
	},
	{
		id: ICON_DASHBOARD_CHART,
		label: "Stats dashboard",
		source: "custom",
		usedIn: [
			"StatsPanel.ts — stats pane icon (opens WordCountModal)",
			"StoryContextView.ts — Story Context Chapter tab word-count chrome (display-only)",
			"TopPanel.ts — series-pane hover icon between the settings cog and plot-threads (opens WordCountModal)",
		],
	},
	{ id: ICON_EXCHANGE, label: "Cycle stats mode", source: "custom", usedIn: [] },
	{ id: ICON_CALENDAR, label: "History", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog (\"calendar-dotted\")"] },
	{
		id: ICON_CALENDAR_EVENT,
		label: "Calendar (event)",
		source: "custom",
		usedIn: [
			"WordCountModal.ts — days heatmap label (display-only)",
			"WordCountModal.ts — stats-pane mode picker (daily)",
		],
	},
	{
		id: ICON_CALENDAR_WEEK,
		label: "Calendar (week)",
		source: "custom",
		usedIn: [
			"WordCountModal.ts — weeks heatmap label (display-only)",
			"WordCountModal.ts — stats-pane mode picker (weekly)",
		],
	},
	{ id: ICON_TOOLS, label: "Tools panel", source: "custom", usedIn: ["ToolsPanel.ts — view tab icon"] },
	{
		id: ICON_FORGE,
		label: "Forge",
		source: "custom",
		usedIn: ["StoryContextView.ts — Story Context's \"Forge family\" tab icon"],
	},
	{
		id: ICON_EYE,
		label: "View chapter",
		source: "custom",
		usedIn: [],
	},
	{
		id: ICON_EYE_DUOTONE,
		label: "Eye (duotone)",
		source: "custom",
		usedIn: [
			"ObsidianElementsModal.ts — hide-or-show row",
			"StoryContextView.ts — Focus Mode Notebook browse child",
		],
	},
	{
		id: ICON_FILE_PLUS,
		label: "Add to chapter",
		source: "custom",
		// Superseded by ICON_ADD_SQUARE on the same button (StoryContextView.ts's "add chapter
		// summary to chapter details" action) — kept registered, just currently unused.
		usedIn: [],
	},
	{
		id: ICON_FILE_TEXT_DUOTONE,
		label: "File text (duotone)",
		source: "custom",
		usedIn: ["protectionsController.ts — recreate storyforge welcome note hover icon (SeriesModal general tab)"],
	},
	{
		id: ICON_OBSIDIAN,
		label: "Obsidian",
		source: "custom",
		usedIn: ["SeriesModal.ts — formatting tab hover icon that opens ObsidianElementsModal"],
	},
	{
		id: ICON_LOCATION_TARGET_SQUARE,
		label: "Location target (square)",
		source: "custom",
		usedIn: [],
	},
	{
		id: ICON_TARGET_DUOTONE,
		label: "Target (duotone)",
		source: "custom",
		usedIn: ["StoryContextView.ts — Story Context Chapter tab's \"go to chapter\" action"],
	},
	{
		id: ICON_REFRESH_SQUARE,
		label: "Refresh (square, text + repeat arrow)",
		source: "custom",
		usedIn: [],
	},
	{
		id: ICON_ADD_SQUARE,
		label: "Add (square)",
		source: "custom",
		usedIn: [],
	},
	{
		id: ICON_CHEVRON_DOWN,
		label: "Expanded section (Charm)",
		source: "custom",
		usedIn: ["NovelPanel.ts — chapter plot card collapse control (expanded)"],
	},
	{
		id: ICON_CHEVRON_RIGHT,
		label: "Collapsed section (Charm)",
		source: "custom",
		usedIn: ["NovelPanel.ts — chapter plot card collapse control (collapsed)"],
	},
	{
		id: ICON_MULTIPLY_SQUARE,
		label: "Clear",
		source: "custom",
		usedIn: [
			"CodexEntryPickerModal.ts — cancel",
			"TypesTagsExportModal.ts — cancel",
			"ThreadsExportModal.ts — cancel",
			"CompleteExportModal.ts — cancel",
			"PreferencesExportModal.ts — cancel",
		],
	},
	{ id: ICON_FOLDER_PLUS, label: "New folder", source: "custom", usedIn: ["BottomPanel.ts — new Codex folder button"] },
	{ id: ICON_FOLDER, label: "Folder", source: "custom", usedIn: ["BottomPanel.ts — Codex folder row icon (plain folders, and lore-folder expand)"] },
	{
		id: ICON_PERSON_FILL,
		label: "Person",
		source: "custom",
		usedIn: ["codex.ts — Codex \"Person\" type icon", "SeriesOverviewView.ts — Default PoV / chapter PoV controls", "iconRegistry.ts — Codex icon catalog"],
	},
	{
		id: ICON_PERSON_FILL_ADD,
		label: "Set PoV",
		source: "custom",
		usedIn: ["BookSynopsisModal.ts — chapter PoV add button", "SeriesOverviewView.ts — Default PoV / chapter PoV controls (unset state)"],
	},
	{ id: ICON_PERSON_2_FILL, label: "Populace", source: "custom", usedIn: ["codex.ts — Codex \"Populace\" type icon", "iconRegistry.ts — Codex icon catalog"] },
	{
		id: ICON_MAP_PIN,
		label: "Place",
		source: "custom",
		usedIn: ["codex.ts — Codex \"Place\" type icon", "BookSynopsisModal.ts — chapter location filled badge", "SeriesOverviewView.ts — chapter location control", "iconRegistry.ts — Codex icon catalog"],
	},
	{
		id: ICON_MAP_PIN_PLUS,
		label: "Set location",
		source: "custom",
		usedIn: ["BookSynopsisModal.ts — chapter location add button", "SeriesOverviewView.ts — chapter location control (unset state)"],
	},
	{
		id: ICON_PLUS_SQUARE,
		label: "New file",
		source: "custom",
		usedIn: [
			"TopPanel.ts — new chapter button (Unplaced Chapters) and new book button (Unplaced Novels)",
			"BottomPanel.ts — new Codex note button",
			"IdeaShelfPanel.ts — new notebook note button",
		],
	},
	{
		id: ICON_MINUS_SQUARE,
		label: "Ignore",
		source: "custom",
		usedIn: [
			"TagRegistryModal.ts — delete type/tag",
			"TagPickerModal.ts — delete tag",
			"CodexSetTypeModal.ts — delete type",
			"IdeaSetTypeModal.ts — delete type",
			"PlotThreadRegistryModal.ts — delete thread",
		],
	},
	{
		id: ICON_MINUS_CIRCLE_DUOTONE,
		label: "Ignore (circle, duotone)",
		source: "custom",
		usedIn: ["StoryContextView.ts — ignore unknown name"],
	},
	{
		id: ICON_CHECK_SQUARE,
		label: "Done / confirm",
		source: "custom",
		usedIn: [
			"StoryContextView.ts — mark detail done",
			"StoryContextView.ts — confirm grey attribution",
			"VaultTagModal.ts — muted sample-row tick standing in for the display checkbox",
		],
	},
	{
		id: ICON_CYCLE_ALT,
		label: "Cycling guide badge",
		source: "custom",
		usedIn: ["cyclingGuide.ts — badge at the bottom-right of each 500-word divider line"],
	},
	{
		id: ICON_DOCUMENT_PAGE_BREAK,
		label: "Cycling guide",
		source: "custom",
		usedIn: ["SeriesModal.ts — general tab hover icon that opens CyclingGuideModal"],
	},
	{
		id: ICON_PLOT_THREADS,
		label: "Plot threads",
		source: "custom",
		usedIn: [
			"TopPanel.ts — series-pane hover icon to the right of stats (opens PlotThreadRegistryModal)",
			"SeriesModal.ts — types, tags, & threads tab hover icon that opens PlotThreadRegistryModal",
		],
	},
	{ id: ICON_PAGE_TEXT, label: "Page text", source: "custom", usedIn: ["TextStyleModal.ts — text format breadcrumb: Body"] },
	{ id: ICON_PAGE_PORTRAIT, label: "Page portrait", source: "custom", usedIn: ["TextStyleModal.ts — text format breadcrumb: Body text"] },
	{ id: ICON_BLOCKQUOTE, label: "Block quote", source: "custom", usedIn: ["TextStyleModal.ts — text format breadcrumb: Quote"] },
	{ id: ICON_LINK2, label: "Link", source: "custom", usedIn: ["TextStyleModal.ts — text format breadcrumb: Links half of Links and lists"] },
	{ id: ICON_LINK2_DUOTONE, label: "Link (duotone)", source: "custom", usedIn: ["StoryContextView.ts — Story Context Chapter tab link unknown name to existing Codex"] },
	{ id: ICON_LIST3_FILLED, label: "List", source: "custom", usedIn: ["TextStyleModal.ts — text format breadcrumb: Lists half of Links and lists"] },
	{ id: ICON_TEXT_HEADER_1, label: "Heading 1", source: "custom", usedIn: ["TextStyleModal.ts — text format breadcrumb: H1"] },
	{ id: ICON_TEXT_HEADER_2, label: "Heading 2", source: "custom", usedIn: ["TextStyleModal.ts — text format breadcrumb: H2"] },
	{ id: ICON_TEXT_HEADER_3, label: "Heading 3", source: "custom", usedIn: ["TextStyleModal.ts — text format breadcrumb: H3"] },
	{ id: ICON_TEXT_HEADER_4_CARET, label: "Headings 4–6", source: "custom", usedIn: ["TextStyleModal.ts — text format breadcrumb: H4–6 group"] },
	{ id: ICON_TEXT_HEADER_4, label: "Heading 4", source: "custom", usedIn: ["TextStyleModal.ts — text format breadcrumb: H4"] },
	{ id: ICON_TEXT_HEADER_5, label: "Heading 5", source: "custom", usedIn: ["TextStyleModal.ts — text format breadcrumb: H5"] },
	{ id: ICON_TEXT_HEADER_6, label: "Heading 6", source: "custom", usedIn: ["TextStyleModal.ts — text format breadcrumb: H6"] },
	{ id: ICON_VERTICAL_SCROLL_POINT, label: "Vertical scroll", source: "custom", usedIn: ["TextStyleModal.ts — text format breadcrumb: Extras"] },
	{ id: ICON_NUMBER_CIRCLE_0, label: "Number 0", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog", "iconRegistry.ts — vault tag icon catalog"] },
	{ id: ICON_NUMBER_CIRCLE_1, label: "Number 1", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog", "iconRegistry.ts — vault tag icon catalog"] },
	{ id: ICON_NUMBER_CIRCLE_2, label: "Number 2", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog", "iconRegistry.ts — vault tag icon catalog"] },
	{ id: ICON_NUMBER_CIRCLE_3, label: "Number 3", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog", "iconRegistry.ts — vault tag icon catalog"] },
	{ id: ICON_NUMBER_CIRCLE_4, label: "Number 4", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog", "iconRegistry.ts — vault tag icon catalog"] },
	{ id: ICON_NUMBER_CIRCLE_5, label: "Number 5", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog", "iconRegistry.ts — vault tag icon catalog"] },
	{ id: ICON_NUMBER_CIRCLE_6, label: "Number 6", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog", "iconRegistry.ts — vault tag icon catalog"] },
	{ id: ICON_NUMBER_CIRCLE_7, label: "Number 7", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog", "iconRegistry.ts — vault tag icon catalog"] },
	{ id: ICON_NUMBER_CIRCLE_8, label: "Number 8", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog", "iconRegistry.ts — vault tag icon catalog"] },
	{ id: ICON_NUMBER_CIRCLE_9, label: "Number 9", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog", "iconRegistry.ts — vault tag icon catalog"] },
	{
		id: ICON_EYE_OUTLINE,
		label: "Eye (outline)",
		source: "custom",
		usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog (distinct from ICON_EYE's filled glyph, used for the \"View chapter\" action button)"],
	},
	{ id: ICON_EXCLAMATION_SQUARE, label: "Warning (square outline)", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{ id: ICON_EXCLAMATION_SQUARE_FILL, label: "Warning (square filled)", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog", "iconRegistry.ts — vault tag icon catalog"] },
	{ id: ICON_INFO_CIRCLE, label: "Info (circle)", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{
		id: ICON_EDIT_PEN,
		label: "Pencil (catalog alias \"pencil\" — asset is the edit-pen glyph)",
		source: "custom",
		usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog (replaced the stock \"pencil\" Lucide icon once formerly in that catalog)"],
	},
	{
		id: ICON_VERIFIED_CHECK,
		label: "Done (outline; catalog alias \"done\")",
		source: "custom",
		usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"],
	},
	{
		id: ICON_VERIFIED_CHECK_FILL,
		label: "Done (filled; catalog alias \"done-fill\")",
		source: "custom",
		usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"],
	},
	{ id: ICON_STARS_FILL, label: "Stars (filled)", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_TRANSPORT_TO_START, label: "Transport: to start (double-up chevron)", source: "custom", usedIn: ["CodexFocusNavigator.ts — left of the chapter list"] },
	{ id: ICON_TRANSPORT_PREVIOUS, label: "Transport: previous chapter (up chevron)", source: "custom", usedIn: ["CodexFocusNavigator.ts — left of the chapter list"] },
	{ id: ICON_TRANSPORT_NEXT, label: "Transport: next chapter (down chevron)", source: "custom", usedIn: ["CodexFocusNavigator.ts — left of the chapter list"] },
	{ id: ICON_TRANSPORT_TO_END, label: "Transport: to end (double-down chevron)", source: "custom", usedIn: ["CodexFocusNavigator.ts — left of the chapter list"] },
	{
		id: ICON_ADD_CIRCLE,
		label: "Add (circle, duotone)",
		source: "custom",
		usedIn: [
			"CodexFocusNavigator.ts — 'continue the story' tile",
			"NewChapterView.ts — full-page create-chapter icon (3em)",
			"StoryContextView.ts — Focus Mode Notebook new-note child",
			"StoryContextView.ts — Story Context Chapter tab add to Codex and create details note",
		],
	},
	{
		id: ICON_LAYOUT_SELECTOR,
		label: "Layout selector",
		source: "custom",
		usedIn: ["iconRegistry.ts — Codex icon catalog"],
	},
	{
		id: ICON_TAG_EDIT,
		label: "Tag (edit)",
		source: "custom",
		usedIn: ["iconRegistry.ts — Codex icon catalog"],
	},
	{
		id: ICON_TAG_DUOTONE,
		label: "Tag (duotone)",
		source: "custom",
		usedIn: [
			"SeriesModal.ts — types, tags, & threads tab hover icon that opens the types manager",
			"TopPanel.ts — series-pane hover icon that opens the types manager",
			"BottomPanel.ts — full-pane Codex tab hover icon that opens the types manager",
		],
	},
	{
		id: ICON_BOOKMARK_DUOTONE,
		label: "Bookmark (duotone)",
		source: "custom",
		usedIn: [
			"SeriesModal.ts — types, tags, & threads tab hover icon that opens chapter and novel tags",
			"TopPanel.ts — series-pane hover icon that opens chapter and novel tags",
		],
	},
	{
		id: ICON_HASHTAG_SQUARE_DUOTONE,
		label: "Hashtag square (duotone)",
		source: "custom",
		usedIn: [
			"BottomPanel.ts — full-pane Codex tab hover icon that opens the vault #tag manager",
			"SeriesModal.ts — types, tags, & threads tab hover icon that opens Codex tags",
		],
	},
	{
		id: ICON_NOTEBOOK,
		label: "Notebook",
		source: "custom",
		usedIn: [],
	},
	{
		id: ICON_STORYTELLING,
		label: "Storytelling book",
		source: "custom",
		usedIn: ["main.ts — ribbon icon opening OnboardingModal"],
	},
	{
		id: ICON_CONTINUOUS_MODE,
		label: "Continuous reading mode (reicon carousel-v-duotone; hover colour while active)",
		source: "custom",
		usedIn: ["CodexFocusNavigator.ts — continuous-mode toggle, right of the chapter list"],
	},
	{
		id: ICON_BOOKSHELF,
		label: "Bookshelf",
		source: "custom",
		usedIn: [],
	},
	{
		id: ICON_CARDS,
		label: "Playing cards (outline)",
		source: "custom",
		usedIn: [],
	},
	{
		id: ICON_BOOK_DUOTONE,
		label: "Book (duotone)",
		source: "custom",
		usedIn: [
			"StoryContextView.ts — Story Context's Novel tab icon",
			"StoryForgeView.ts — layout tab row, leading icon on the \"Novel\" tab",
			"NovelOverviewView.ts — main-pane Novel overview page's own tab icon",
			"WordCountModal.ts — stats-pane mode picker (novel)",
			"archivePanel.ts — Archive Novel-mode icon",
		],
	},
	{
		id: ICON_BOOK_OPEN_FILLED,
		label: "Book open (filled)",
		source: "custom",
		usedIn: [
			"StoryContextView.ts — Story Context's Chapter tab icon and Focus Mode word-count chrome",
			"StoryForgeView.ts — layout tab row, leading icon on the \"Chapter\" tab",
			"WordCountModal.ts — stats-pane mode picker (chapter)",
		],
	},
	{
		id: ICON_CLIPBOARD_LIST_DUOTONE,
		label: "Clipboard list (duotone)",
		source: "custom",
		usedIn: ["StoryContextView.ts — Notebook source rail Dossier icon"],
	},
	{
		id: ICON_CLIPBOARD_ADD_DUOTONE,
		label: "Clipboard add (duotone)",
		source: "custom",
		usedIn: [],
	},
	{
		id: ICON_CLIPBOARD_TEXT_DUOTONE,
		label: "Clipboard text (duotone)",
		source: "custom",
		usedIn: [],
	},
	{
		id: ICON_CLIPBOARD_DUOTONE,
		label: "Clipboard (duotone)",
		source: "custom",
		usedIn: [],
	},
	{
		id: ICON_NOTEBOOK_DUOTONE,
		label: "Notebook (duotone)",
		source: "custom",
		usedIn: [
			"StoryContextView.ts — Story Context Notebook tab, Focus Mode Notebook trigger, Notebook pane notebook-index switcher, Archive source rail",
			"archivePanel.ts — Archive Notebook-mode icon",
			"TagRegistryModal.ts — types manager Notebook tab",
		],
	},
	{
		id: ICON_DOSSIER,
		label: "Dossier (bill duotone)",
		source: "custom",
		usedIn: ["UiFormattingModal.ts — story-context dossier formatting leaf"],
	},
	{
		id: ICON_ARCHIVE_FILLED,
		label: "Archive (filled box)",
		source: "custom",
		usedIn: [
			"TagRegistryModal.ts — types manager Archive tab",
			"TypesTagsExportModal.ts / PreferencesExportModal.ts / ThreadsExportModal.ts / CompleteExportModal.ts — archive-preset hover icon",
		],
	},
	{
		id: ICON_X,
		label: "X",
		source: "custom",
		usedIn: ["archivePanel.ts — empty Archive list glyph"],
	},
	{
		id: ICON_TAG,
		label: "Tag",
		source: "custom",
		usedIn: [
			"tagRegistry.ts — resolveIconAlias's fallback for a stale/unknown icon alias",
			"TagRegistryModal.ts / TagPickerModal.ts — \"+ New tag\" row's placeholder icon before one is picked",
			"VaultTagModal.ts — sample-row placeholder icon and the glyph before a vault #tag has one picked",
		],
	},
	{ id: ICON_SHOP, label: "Shop", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{
		id: ICON_SETTINGS_GEAR,
		label: "Settings (gear)",
		source: "custom",
		usedIn: ["iconRegistry.ts — Codex icon catalog (distinct from ICON_FILTER's funnel-lines glyph)"],
	},
	{ id: ICON_FIRE, label: "Fire", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_CROWN, label: "Crown", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{
		id: ICON_CALENDAR_PLAIN,
		label: "Calendar (plain)",
		source: "custom",
		usedIn: ["iconRegistry.ts — Codex icon catalog (distinct from ICON_CALENDAR's dotted variant)"],
	},
	{ id: ICON_BUILDING_A, label: "Building A", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_BUILDING_B, label: "Building B", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{
		id: ICON_BOOKMARK,
		label: "Bookmark",
		source: "custom",
		usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog", "iconRegistry.ts — Codex icon catalog"],
	},
	{
		id: ICON_BOOKMARK_FILL,
		label: "Bookmark (filled)",
		source: "custom",
		usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog", "iconRegistry.ts — Codex icon catalog", "iconRegistry.ts — vault tag icon catalog"],
	},
	{ id: ICON_TRUCK, label: "Truck", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_ROCKETSHIP, label: "Rocketship", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_PLANE, label: "Plane", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_SHIP, label: "Ship", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_ROAD, label: "Road", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_MOUNTAIN, label: "Mountain", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{
		id: ICON_TOWER_BLOCK,
		label: "Tower (block)",
		source: "custom",
		usedIn: ["iconRegistry.ts — Codex icon catalog (one of three tower variants — block/slim/fortress)"],
	},
	{
		id: ICON_TOWER_SLIM,
		label: "Tower (slim)",
		source: "custom",
		usedIn: ["iconRegistry.ts — Codex icon catalog (one of three tower variants — block/slim/fortress)"],
	},
	{
		id: ICON_TOWER_FORTRESS,
		label: "Tower (fortress)",
		source: "custom",
		usedIn: ["iconRegistry.ts — Codex icon catalog (one of three tower variants — block/slim/fortress)"],
	},
	{ id: ICON_SHIELD, label: "Shield", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{
		id: ICON_GEARS,
		label: "Gears",
		source: "custom",
		usedIn: ["iconRegistry.ts — Codex icon catalog (two interlocking gears, distinct from ICON_SETTINGS_GEAR's single gear)"],
	},
	{ id: ICON_EXPLOSION, label: "Explosion", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{
		id: ICON_SWORDS_CROSSED,
		label: "Swords (crossed)",
		source: "custom",
		usedIn: ["iconRegistry.ts — Codex icon catalog (distinct from ICON_SWORD's single blade)"],
	},
	{ id: ICON_SWORD, label: "Sword", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_AXE, label: "Axe", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_MAGIC_WAND, label: "Magic wand", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_SUN_FILL, label: "Sun (filled)", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_THUNDERSTORM, label: "Thunderstorm", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_SNOW, label: "Snow", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_RAIN, label: "Rain", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_RIVER, label: "River", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_DEAD_TREE, label: "Dead tree", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_PINE_TREE, label: "Pine tree", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_TREE, label: "Tree", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_BOWL_RICE, label: "Bowl of rice", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_BOWL, label: "Bowl", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_EGG, label: "Egg", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_DRAGON, label: "Dragon", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_UNICORN, label: "Unicorn", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_FISH, label: "Fish", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_PAW, label: "Paw print", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_SKULL, label: "Skull", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_MUSIC_NOTE, label: "Music note", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{
		id: ICON_SPEECH_BUBBLE,
		label: "Speech bubble",
		source: "custom",
		usedIn: ["iconRegistry.ts — Codex icon catalog (distinct from ICON_MESSAGE's message-bubble glyph)"],
	},
	{ id: ICON_SCROLL, label: "Scroll", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_SPARKLES, label: "Sparkles", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_STARS_TRIO, label: "Stars (trio)", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_PERSON_3_FILL, label: "Three people", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_PAW_ROUNDED, label: "Paw print (rounded)", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_CITY, label: "City", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_FIREWORKS, label: "Fireworks", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_GALAXY_OUTLINE, label: "Galaxy (outline)", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_GALAXY_FILL, label: "Galaxy (filled)", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_FOREST, label: "Forest", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_CASTLE, label: "Castle", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_PLANET, label: "Planet", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_TEMPLE, label: "Temple", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_LIGHTNING, label: "Lightning", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_BUILDING_C, label: "Building (outline)", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{
		id: ICON_CHECK_CIRCLE,
		label: "Circle tick",
		source: "custom",
		usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog (replaced the stock \"check-circle\" Lucide icon formerly in that catalog)"],
	},
	{ id: ICON_CHECK_CIRCLE_FILL, label: "Circle tick (filled)", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{
		id: ICON_FLAG,
		label: "Flag",
		source: "custom",
		usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog (replaced the stock \"flag\" Lucide icon formerly in that catalog)"],
	},
	{ id: ICON_FLAG_FILL, label: "Flag (filled)", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog", "iconRegistry.ts — vault tag icon catalog"] },
	{
		id: ICON_STAR_OUTLINE,
		label: "Star (outline)",
		source: "custom",
		usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog (replaced the stock \"star\" Lucide icon formerly in that catalog)"],
	},
	{ id: ICON_STAR_FILL, label: "Star (filled)", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog", "iconRegistry.ts — vault tag icon catalog"] },
	{ id: ICON_STAR_DUOTONE, label: "Star (duotone)", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog", "iconRegistry.ts — vault tag icon catalog"] },
	{
		id: ICON_LOCK,
		label: "Lock",
		source: "custom",
		usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog (replaced the stock \"lock\" Lucide icon formerly in that catalog)"],
	},
	{ id: ICON_HEART_CIRCLE, label: "Heart circle (outline)", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{ id: ICON_HEART_CIRCLE_FILL, label: "Heart circle (filled)", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{ id: ICON_HEART_OUTLINE, label: "Heart (outline)", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{ id: ICON_HEART_FILL, label: "Heart (filled)", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog", "iconRegistry.ts — vault tag icon catalog"] },
	{ id: ICON_MESSAGE, label: "Message", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },

	// Stock (Lucide icons bundled with Obsidian, referenced by name)
	{
		id: "grip-vertical",
		label: "Drag handle",
		source: "lucide",
		usedIn: [
			"SeriesModal.ts — book row drag handle",
			"TopPanel.ts — row drag handle",
			"TagRegistryModal.ts / TagPickerModal.ts — tag row drag handle",
			"VaultTagModal.ts — vault #tag row drag handle",
			// BottomPanel.ts no longer has one — the Codex tree's whole row is now the drag target
			// (dragReorderTree.ts), not a grip handle. See that file's revertable-feature-test note.
		],
	},
	{
		id: "chevron-right",
		label: "Collapsed section",
		source: "lucide",
		usedIn: ["BottomPanel.ts — Codex folder collapse chevron"],
	},
	{
		id: "chevron-down",
		label: "Expanded section",
		source: "lucide",
		usedIn: ["BottomPanel.ts — Codex folder collapse chevron"],
	},
];
