import {
	ICON_ADD_CIRCLE,
	ICON_ADD_SQUARE,
	ICON_ARCHIVE,
	ICON_AXE,
	ICON_BOOK_OPEN,
	ICON_BOOK_PLUS,
	ICON_BOOK_SPINE,
	ICON_BOOKMARK,
	ICON_BOOKMARK_FILL,
	ICON_BOWL,
	ICON_BOWL_RICE,
	ICON_BUILDING_A,
	ICON_BUILDING_B,
	ICON_CALENDAR,
	ICON_CALENDAR_PLAIN,
	ICON_CHECK_CIRCLE,
	ICON_CHECK_CIRCLE_FILL,
	ICON_CODEX,
	ICON_CONTINUOUS_MODE,
	ICON_CONTINUOUS_MODE_EXIT,
	ICON_CROWN,
	ICON_CYCLE_ALT,
	ICON_DASHBOARD_CHART,
	ICON_DEAD_TREE,
	ICON_DRAGON,
	ICON_EDIT_PEN,
	ICON_EGG,
	ICON_EXCHANGE,
	ICON_EXCLAMATION_SQUARE,
	ICON_EXCLAMATION_SQUARE_FILL,
	ICON_EXPLOSION,
	ICON_EYE,
	ICON_EYE_OUTLINE,
	ICON_FILE_PLUS,
	ICON_FILTER,
	ICON_FILTER_LIST,
	ICON_FIRE,
	ICON_FISH,
	ICON_FLAG,
	ICON_FLAG_FILL,
	ICON_FOLDER_PLUS,
	ICON_FORGE,
	ICON_GEARS,
	ICON_HEART_CIRCLE,
	ICON_HEART_CIRCLE_FILL,
	ICON_HEART_FILL,
	ICON_HEART_OUTLINE,
	ICON_INFO_CIRCLE,
	ICON_LAYOUT_SELECTOR,
	ICON_LOCATION_TARGET_SQUARE,
	ICON_LOCK,
	ICON_MAGIC_WAND,
	ICON_MAP_PIN,
	ICON_MAP_PIN_PLUS,
	ICON_MESSAGE,
	ICON_MOUNTAIN,
	ICON_MULTIPLY_SQUARE,
	ICON_MUSIC_NOTE,
	ICON_NOTEBOOK,
	ICON_NUMBER_CIRCLE_0,
	ICON_NUMBER_CIRCLE_1,
	ICON_NUMBER_CIRCLE_2,
	ICON_NUMBER_CIRCLE_3,
	ICON_NUMBER_CIRCLE_4,
	ICON_NUMBER_CIRCLE_5,
	ICON_NUMBER_CIRCLE_6,
	ICON_NUMBER_CIRCLE_7,
	ICON_NUMBER_CIRCLE_8,
	ICON_NUMBER_CIRCLE_9,
	ICON_PAW,
	ICON_PERSON_2_FILL,
	ICON_PERSON_FILL,
	ICON_PERSON_FILL_ADD,
	ICON_PINE_TREE,
	ICON_PLANE,
	ICON_PLUS_SQUARE,
	ICON_MINUS_SQUARE,
	ICON_CHECK_SQUARE,
	ICON_RAIN,
	ICON_REFRESH_SQUARE,
	ICON_RIVER,
	ICON_ROAD,
	ICON_ROCKETSHIP,
	ICON_SCROLL,
	ICON_SERIES,
	ICON_SETTINGS_GEAR,
	ICON_SHIELD,
	ICON_SHIP,
	ICON_SHOP,
	ICON_SKULL,
	ICON_SNOW,
	ICON_SPEECH_BUBBLE,
	ICON_STAR_DUOTONE,
	ICON_STAR_FILL,
	ICON_STAR_OUTLINE,
	ICON_STARS_FILL,
	ICON_STORYTELLING,
	ICON_SUN_FILL,
	ICON_SWORD,
	ICON_SWORDS_CROSSED,
	ICON_TAG,
	ICON_TAG_EDIT,
	ICON_THUNDERSTORM,
	ICON_TIMELINE,
	ICON_TOOLS,
	ICON_TOWER_BLOCK,
	ICON_TOWER_FORTRESS,
	ICON_TOWER_SLIM,
	ICON_TRANSPORT_NEXT,
	ICON_TRANSPORT_PREVIOUS,
	ICON_TRANSPORT_TO_END,
	ICON_TRANSPORT_TO_START,
	ICON_TREE,
	ICON_TRUCK,
	ICON_UNARCHIVE,
	ICON_UNICORN,
	ICON_UNPLACED,
	ICON_VERIFIED_CHECK,
	ICON_VERIFIED_CHECK_FILL,
} from "./icons";

/** One entry in a fixed, programmer-curated icon catalog. Not user-extensible — end users pick
 * from these lists (via IconPickerModal) but never add to them; only a code change (adding an
 * entry here, plus a corresponding icon in icons.ts) grows a catalog. */
export interface IconCatalogEntry {
	alias: string;
	label: string;
	iconId: string;
}

/**
 * Icon choices for Codex types (Person/Place/Populace, and anything a user adds alongside them —
 * including nested types under Person/Place, see TagDefinition.parentId). Themed around "kinds of
 * things a story world has": people, places, roles, institutions, transport, geography,
 * conflict/magic (the last two chosen with nested types like Hero/Villain in mind), weather,
 * food, and creatures/mythical beings.
 */
export const CODEX_ICON_CATALOG: IconCatalogEntry[] = [
	{ alias: "person-fill", label: "Person", iconId: ICON_PERSON_FILL },
	{ alias: "location-pin", label: "Location pin", iconId: ICON_MAP_PIN },
	{ alias: "person-2-fill", label: "Two people", iconId: ICON_PERSON_2_FILL },
	{ alias: "stars", label: "Stars", iconId: ICON_STARS_FILL },
	{ alias: "shop", label: "Shop", iconId: ICON_SHOP },
	{ alias: "settings-gear", label: "Gear", iconId: ICON_SETTINGS_GEAR },
	{ alias: "fire", label: "Fire", iconId: ICON_FIRE },
	{ alias: "earth", label: "Earth", iconId: ICON_CODEX },
	{ alias: "crown", label: "Crown", iconId: ICON_CROWN },
	{ alias: "calendar-plain", label: "Calendar", iconId: ICON_CALENDAR_PLAIN },
	{ alias: "calendar-dotted", label: "Calendar (dated)", iconId: ICON_CALENDAR },
	{ alias: "building-a", label: "Building", iconId: ICON_BUILDING_A },
	{ alias: "building-b", label: "Building (tall)", iconId: ICON_BUILDING_B },
	{ alias: "bookmark", label: "Bookmark", iconId: ICON_BOOKMARK },
	{ alias: "bookmark-fill", label: "Bookmark (filled)", iconId: ICON_BOOKMARK_FILL },
	{ alias: "truck", label: "Truck", iconId: ICON_TRUCK },
	{ alias: "rocketship", label: "Rocketship", iconId: ICON_ROCKETSHIP },
	{ alias: "plane", label: "Plane", iconId: ICON_PLANE },
	{ alias: "ship", label: "Ship", iconId: ICON_SHIP },
	{ alias: "road", label: "Road", iconId: ICON_ROAD },
	{ alias: "mountain", label: "Mountain", iconId: ICON_MOUNTAIN },
	{ alias: "tower-block", label: "Tower (block)", iconId: ICON_TOWER_BLOCK },
	{ alias: "tower-slim", label: "Tower (slim)", iconId: ICON_TOWER_SLIM },
	{ alias: "tower-fortress", label: "Tower (fortress)", iconId: ICON_TOWER_FORTRESS },
	{ alias: "shield", label: "Shield", iconId: ICON_SHIELD },
	{ alias: "gears", label: "Gears", iconId: ICON_GEARS },
	{ alias: "explosion", label: "Explosion", iconId: ICON_EXPLOSION },
	{ alias: "swords-crossed", label: "Swords (crossed)", iconId: ICON_SWORDS_CROSSED },
	{ alias: "sword", label: "Sword", iconId: ICON_SWORD },
	{ alias: "axe", label: "Axe", iconId: ICON_AXE },
	{ alias: "magic-wand", label: "Magic wand", iconId: ICON_MAGIC_WAND },
	{ alias: "sun-fill", label: "Sun", iconId: ICON_SUN_FILL },
	{ alias: "thunderstorm", label: "Thunderstorm", iconId: ICON_THUNDERSTORM },
	{ alias: "snow", label: "Snow", iconId: ICON_SNOW },
	{ alias: "rain", label: "Rain", iconId: ICON_RAIN },
	{ alias: "river", label: "River", iconId: ICON_RIVER },
	{ alias: "dead-tree", label: "Dead tree", iconId: ICON_DEAD_TREE },
	{ alias: "pine-tree", label: "Pine tree", iconId: ICON_PINE_TREE },
	{ alias: "tree", label: "Tree", iconId: ICON_TREE },
	{ alias: "bowl-rice", label: "Bowl of rice", iconId: ICON_BOWL_RICE },
	{ alias: "bowl", label: "Bowl", iconId: ICON_BOWL },
	{ alias: "egg", label: "Egg", iconId: ICON_EGG },
	{ alias: "dragon", label: "Dragon", iconId: ICON_DRAGON },
	{ alias: "unicorn", label: "Unicorn", iconId: ICON_UNICORN },
	{ alias: "fish", label: "Fish", iconId: ICON_FISH },
	{ alias: "paw", label: "Paw print", iconId: ICON_PAW },
	{ alias: "skull", label: "Skull", iconId: ICON_SKULL },
	{ alias: "music-note", label: "Music note", iconId: ICON_MUSIC_NOTE },
	{ alias: "speech-bubble", label: "Speech bubble", iconId: ICON_SPEECH_BUBBLE },
	{ alias: "scroll", label: "Scroll", iconId: ICON_SCROLL },
];

/**
 * Icon choices for chapter tags and novel tags — a shared pool, themed around editing/review
 * status: reference/status (done, done-fill, circle-tick, circle-tick-fill, info), progress
 * (number-0 through number-9 — handy for "editing pass N"-style tags), reaction (heart-circle,
 * heart-circle-fill, heart-outline, heart-fill), editing (pencil), priority (star, star-duotone,
 * star-fill), marking (bookmark, bookmark-fill), flags (flag, flag-fill), and warnings
 * (warning-square, warning-square-fill). Order here is also IconPickerModal's display order for
 * this list, chosen deliberately (see the modal's own doc comment) — eye-watching, message, and
 * lock don't fit any of those groups cleanly and sit at the end. Exactly 32 entries, an 8x4 grid
 * in the picker.
 *
 * Every entry here is a custom SVG (see src/icons.ts) — no stock Lucide icons remain in this
 * catalog as of the circle-tick/flag/star/lock replacements.
 */
export const TAG_ICON_CATALOG: IconCatalogEntry[] = [
	{ alias: "done", label: "Done", iconId: ICON_VERIFIED_CHECK },
	{ alias: "done-fill", label: "Done (filled)", iconId: ICON_VERIFIED_CHECK_FILL },
	{ alias: "circle-tick", label: "Circle tick", iconId: ICON_CHECK_CIRCLE },
	{ alias: "circle-tick-fill", label: "Circle tick (filled)", iconId: ICON_CHECK_CIRCLE_FILL },
	{ alias: "info", label: "Info", iconId: ICON_INFO_CIRCLE },
	{ alias: "number-0", label: "Number 0", iconId: ICON_NUMBER_CIRCLE_0 },
	{ alias: "number-1", label: "Number 1", iconId: ICON_NUMBER_CIRCLE_1 },
	{ alias: "number-2", label: "Number 2", iconId: ICON_NUMBER_CIRCLE_2 },
	{ alias: "number-3", label: "Number 3", iconId: ICON_NUMBER_CIRCLE_3 },
	{ alias: "number-4", label: "Number 4", iconId: ICON_NUMBER_CIRCLE_4 },
	{ alias: "number-5", label: "Number 5", iconId: ICON_NUMBER_CIRCLE_5 },
	{ alias: "number-6", label: "Number 6", iconId: ICON_NUMBER_CIRCLE_6 },
	{ alias: "number-7", label: "Number 7", iconId: ICON_NUMBER_CIRCLE_7 },
	{ alias: "number-8", label: "Number 8", iconId: ICON_NUMBER_CIRCLE_8 },
	{ alias: "number-9", label: "Number 9", iconId: ICON_NUMBER_CIRCLE_9 },
	{ alias: "heart-circle", label: "Heart circle", iconId: ICON_HEART_CIRCLE },
	{ alias: "heart-circle-fill", label: "Heart circle (filled)", iconId: ICON_HEART_CIRCLE_FILL },
	{ alias: "heart-outline", label: "Heart (outline)", iconId: ICON_HEART_OUTLINE },
	{ alias: "heart-fill", label: "Heart (filled)", iconId: ICON_HEART_FILL },
	{ alias: "pencil", label: "Pencil", iconId: ICON_EDIT_PEN },
	{ alias: "star", label: "Star", iconId: ICON_STAR_OUTLINE },
	{ alias: "star-duotone", label: "Star (duotone)", iconId: ICON_STAR_DUOTONE },
	{ alias: "star-fill", label: "Star (filled)", iconId: ICON_STAR_FILL },
	{ alias: "bookmark", label: "Bookmark", iconId: ICON_BOOKMARK },
	{ alias: "bookmark-fill", label: "Bookmark (filled)", iconId: ICON_BOOKMARK_FILL },
	{ alias: "flag", label: "Flag", iconId: ICON_FLAG },
	{ alias: "flag-fill", label: "Flag (filled)", iconId: ICON_FLAG_FILL },
	{ alias: "warning-square", label: "Warning (square)", iconId: ICON_EXCLAMATION_SQUARE },
	{ alias: "warning-square-fill", label: "Warning (filled square)", iconId: ICON_EXCLAMATION_SQUARE_FILL },
	{ alias: "eye-watching", label: "Eye", iconId: ICON_EYE_OUTLINE },
	{ alias: "message", label: "Message", iconId: ICON_MESSAGE },
	{ alias: "lock", label: "Lock", iconId: ICON_LOCK },
];

export interface IconRegistryEntry {
	id: string;
	label: string;
	source: "custom" | "lucide";
	/** Where this icon is currently wired up, as "File.ts — what it is". Empty means nothing in the app renders it. */
	usedIn: string[];
}

/**
 * Standing rule for any icon shown alongside others at a shared, uniform CSS box size (a transport
 * row, an icon-picker grid, anything with a "these should all look the same size" expectation):
 * match the *painted fraction of the viewBox*, not the viewBox's own size. Two icons can share an
 * identical `width`/`height` box and still read as mismatched if one artwork is inset within its
 * own viewBox (a ring with a gap to the edge) and the other runs edge-to-edge — the continuous-mode
 * toggle icons hit exactly this (their 26-unit artwork touched all four sides of its own viewBox,
 * while the transport icons' rings are inset by design), and padding the box in icons.ts's
 * CONTINUOUS_MODE_SVG/CONTINUOUS_MODE_EXIT_SVG to match the transport set's painted fraction was
 * the actual fix — not a per-button forced pixel size in JS, which is what papered over it before.
 */

/**
 * Hand-maintained inventory of every icon storyForge renders, custom or stock.
 * There's no way to determine "used or not" by inspecting the compiled plugin
 * at runtime, so this list is the source of truth — update it whenever an
 * icon is added, removed, or rewired to a different spot in the UI.
 */
export const ICON_REGISTRY: IconRegistryEntry[] = [
	// Custom (registered via addIcon in icons.ts)
	{ id: ICON_UNPLACED, label: "Unplaced", source: "custom", usedIn: ["TopPanel.ts — Unplaced section header (books & chapters)"] },
	{
		id: ICON_ARCHIVE,
		label: "Archive",
		source: "custom",
		usedIn: [
			"RecommendationView.ts — Archive tab (Novel/Chapter/Details/Dossier row) and the embedded archive pane's own header",
			"ArchiveView.ts — legacy Archive leaf header (detached from rail)",
		],
	},
	{
		id: ICON_UNARCHIVE,
		label: "Unarchive",
		source: "custom",
		usedIn: ["archivePanel.ts — unarchive row button"],
	},
	{ id: ICON_CODEX, label: "Codex", source: "custom", usedIn: ["BottomPanel.ts — Codex panel header", "iconRegistry.ts — Codex icon catalog (\"earth\")"] },
	{
		id: ICON_SERIES,
		label: "Series",
		source: "custom",
		usedIn: [
			"StoryForgeView.ts — view tab icon; also the layout tab row's \"Series\" tab icon",
			"SeriesOverviewView.ts — view tab icon",
		],
	},
	{
		id: ICON_FILTER,
		label: "Settings",
		source: "custom",
		usedIn: [
			"TopPanel.ts — series-mode settings button (opens SeriesModal; Series layout only)",
			"uiStylePreviewSample.ts — settings-tab live style preview mockup",
		],
	},
	{
		id: ICON_FILTER_LIST,
		label: "Filter list",
		source: "custom",
		usedIn: ["BottomPanel.ts — Codex tree type-filter button"],
	},
	{
		id: ICON_TIMELINE,
		label: "Synopsis and plot",
		source: "custom",
		usedIn: [
			"TopPanel.ts — book synopsis/plot settings button",
			"RecommendationView.ts — Story Context's Novel tab, \"Plot\" section header line",
			"SeriesOverviewView.ts — \"Plot\" section header line",
		],
	},
	{
		id: ICON_BOOK_PLUS,
		label: "New book",
		source: "custom",
		usedIn: ["TopPanel.ts — new book button (Unplaced header)", "SeriesModal.ts — add book button"],
	},
	{
		id: ICON_BOOK_OPEN,
		label: "Open book",
		source: "custom",
		usedIn: [
			"TopPanel.ts — Series tab's book list, marks the currently open/selected novel",
			"StoryForgeView.ts — layout tab row, leading icon on the \"Detailed\" tab",
			"StorytellingView.ts — view tab icon",
		],
	},
	{
		id: ICON_BOOK_SPINE,
		label: "Book (spine)",
		source: "custom",
		usedIn: [],
	},
	{ id: ICON_DASHBOARD_CHART, label: "Stats dashboard", source: "custom", usedIn: ["StatsPanel.ts — stats header"] },
	{ id: ICON_EXCHANGE, label: "Cycle stats mode", source: "custom", usedIn: ["StatsPanel.ts — mode switch button"] },
	{ id: ICON_CALENDAR, label: "History", source: "custom", usedIn: ["StatsPanel.ts — history button", "iconRegistry.ts — Codex icon catalog (\"calendar-dotted\")"] },
	{ id: ICON_TOOLS, label: "Tools panel", source: "custom", usedIn: ["ToolsPanel.ts — view tab icon"] },
	{
		id: ICON_FORGE,
		label: "Forge",
		source: "custom",
		usedIn: ["ForgeView.ts — Forge right-rail tab icon"],
	},
	{
		id: ICON_EYE,
		label: "View chapter",
		source: "custom",
		// Superseded by ICON_LOCATION_TARGET_SQUARE on the same button (RecommendationView.ts's
		// "go to chapter" action) — kept registered, just currently unused.
		usedIn: [],
	},
	{
		id: ICON_FILE_PLUS,
		label: "Add to chapter",
		source: "custom",
		// Superseded by ICON_ADD_SQUARE on the same button (RecommendationView.ts's "add chapter
		// summary to chapter details" action) — kept registered, just currently unused.
		usedIn: [],
	},
	{
		id: ICON_LOCATION_TARGET_SQUARE,
		label: "Location target (square)",
		source: "custom",
		usedIn: ["RecommendationView.ts — Story Context Chapter tab's \"go to chapter\" action (replaces ICON_EYE)"],
	},
	{
		id: ICON_REFRESH_SQUARE,
		label: "Refresh (square, text + repeat arrow)",
		source: "custom",
		usedIn: ["RecommendationView.ts — Story Context Chapter tab's \"refresh story context\" action (replaces the stock \"refresh-cw\" Lucide icon)"],
	},
	{
		id: ICON_ADD_SQUARE,
		label: "Add (square)",
		source: "custom",
		usedIn: [
			"RecommendationView.ts — Story Context Chapter tab's \"add chapter summary to chapter details\" action (replaces ICON_FILE_PLUS)",
		],
	},
	{
		id: ICON_MULTIPLY_SQUARE,
		label: "Clear",
		source: "custom",
		usedIn: ["RecommendationView.ts — clear selected dossier entity"],
	},
	{ id: ICON_FOLDER_PLUS, label: "New folder", source: "custom", usedIn: ["BottomPanel.ts — new Codex folder button"] },
	{
		id: ICON_PERSON_FILL,
		label: "Person",
		source: "custom",
		usedIn: ["codex.ts — Codex \"Person\" type icon", "SeriesOverviewView.ts — Default PoV / chapter PoV controls", "iconRegistry.ts — Codex icon catalog"],
	},
	{
		id: ICON_PERSON_FILL_ADD,
		label: "Set PoV",
		source: "custom",
		usedIn: ["BookSynopsisModal.ts — chapter PoV add button", "SeriesOverviewView.ts — Default PoV / chapter PoV controls (unset state)"],
	},
	{ id: ICON_PERSON_2_FILL, label: "Populace", source: "custom", usedIn: ["codex.ts — Codex \"Populace\" type icon", "iconRegistry.ts — Codex icon catalog"] },
	{
		id: ICON_MAP_PIN,
		label: "Place",
		source: "custom",
		usedIn: ["codex.ts — Codex \"Place\" type icon", "BookSynopsisModal.ts — chapter location filled badge", "SeriesOverviewView.ts — chapter location control", "iconRegistry.ts — Codex icon catalog"],
	},
	{
		id: ICON_MAP_PIN_PLUS,
		label: "Set location",
		source: "custom",
		usedIn: ["BookSynopsisModal.ts — chapter location add button", "SeriesOverviewView.ts — chapter location control (unset state)"],
	},
	{
		id: ICON_PLUS_SQUARE,
		label: "New file",
		source: "custom",
		usedIn: [
			"TopPanel.ts — new chapter button (default)",
			"BottomPanel.ts — new Codex note button",
			"RecommendationView.ts — create in Codex (unknown name)",
		],
	},
	{
		id: ICON_MINUS_SQUARE,
		label: "Ignore",
		source: "custom",
		usedIn: [
			"RecommendationView.ts — ignore unknown name",
			"RecommendationView.ts — ignore detail (solid)",
			"RecommendationView.ts — ignore detail attribution (grey)",
		],
	},
	{
		id: ICON_CHECK_SQUARE,
		label: "Done / confirm",
		source: "custom",
		usedIn: [
			"RecommendationView.ts — mark detail done",
			"RecommendationView.ts — confirm grey attribution",
		],
	},
	{
		id: ICON_CYCLE_ALT,
		label: "Cycling guide badge",
		source: "custom",
		usedIn: ["cyclingGuide.ts — badge at the bottom-right of each 500-word divider line"],
	},
	{ id: ICON_NUMBER_CIRCLE_0, label: "Number 0", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{ id: ICON_NUMBER_CIRCLE_1, label: "Number 1", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{ id: ICON_NUMBER_CIRCLE_2, label: "Number 2", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{ id: ICON_NUMBER_CIRCLE_3, label: "Number 3", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{ id: ICON_NUMBER_CIRCLE_4, label: "Number 4", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{ id: ICON_NUMBER_CIRCLE_5, label: "Number 5", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{ id: ICON_NUMBER_CIRCLE_6, label: "Number 6", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{ id: ICON_NUMBER_CIRCLE_7, label: "Number 7", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{ id: ICON_NUMBER_CIRCLE_8, label: "Number 8", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{ id: ICON_NUMBER_CIRCLE_9, label: "Number 9", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{
		id: ICON_EYE_OUTLINE,
		label: "Eye (outline)",
		source: "custom",
		usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog (distinct from ICON_EYE's filled glyph, used for the \"View chapter\" action button)"],
	},
	{ id: ICON_EXCLAMATION_SQUARE, label: "Warning (square outline)", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{ id: ICON_EXCLAMATION_SQUARE_FILL, label: "Warning (square filled)", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{ id: ICON_INFO_CIRCLE, label: "Info (circle)", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{
		id: ICON_EDIT_PEN,
		label: "Pencil (catalog alias \"pencil\" — asset is the edit-pen glyph)",
		source: "custom",
		usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog (replaced the stock \"pencil\" Lucide icon once formerly in that catalog)"],
	},
	{
		id: ICON_VERIFIED_CHECK,
		label: "Done (outline; catalog alias \"done\")",
		source: "custom",
		usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"],
	},
	{
		id: ICON_VERIFIED_CHECK_FILL,
		label: "Done (filled; catalog alias \"done-fill\")",
		source: "custom",
		usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"],
	},
	{ id: ICON_STARS_FILL, label: "Stars (filled)", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_TRANSPORT_TO_START, label: "Transport: to start", source: "custom", usedIn: ["CodexFocusNavigator.ts — transport row"] },
	{ id: ICON_TRANSPORT_PREVIOUS, label: "Transport: previous chapter", source: "custom", usedIn: ["CodexFocusNavigator.ts — transport row"] },
	{ id: ICON_TRANSPORT_NEXT, label: "Transport: next chapter", source: "custom", usedIn: ["CodexFocusNavigator.ts — transport row"] },
	{ id: ICON_TRANSPORT_TO_END, label: "Transport: to end", source: "custom", usedIn: ["CodexFocusNavigator.ts — transport row"] },
	{
		id: ICON_ADD_CIRCLE,
		label: "Add (circle, duotone)",
		source: "custom",
		usedIn: ["CodexFocusNavigator.ts — 'continue the story' tile", "NewChapterView.ts — full-page create-chapter icon (3em)"],
	},
	{
		id: ICON_LAYOUT_SELECTOR,
		label: "Open storyForge interface",
		source: "custom",
		usedIn: [
			"main.ts — ribbon icon (repurposed from the storyLibrary panel's old \"choose layout\" dropdown, now a tab row — see ICON_SERIES's sibling tabs in StoryForgeView.ts)",
		],
	},
	{
		id: ICON_TAG_EDIT,
		label: "Open Tags & Codex types",
		source: "custom",
		usedIn: ["main.ts — ribbon icon"],
	},
	{
		id: ICON_NOTEBOOK,
		label: "Notebook",
		source: "custom",
		usedIn: ["RecommendationView.ts — Story Context view tab icon"],
	},
	{
		id: ICON_STORYTELLING,
		label: "Storytelling book",
		source: "custom",
		usedIn: ["StoryForgeView.ts — layout tab row, leading icon on the \"Novel\" tab"],
	},
	{
		id: ICON_CONTINUOUS_MODE,
		label: "Continuous mode (off — click to enter)",
		source: "custom",
		usedIn: ["CodexFocusNavigator.ts — transport row's fifth control"],
	},
	{
		id: ICON_CONTINUOUS_MODE_EXIT,
		label: "Continuous mode (on — click to exit)",
		source: "custom",
		usedIn: ["CodexFocusNavigator.ts — transport row's fifth control, while continuous mode is active"],
	},
	{
		id: ICON_TAG,
		label: "Tag",
		source: "custom",
		usedIn: [
			"tagRegistry.ts — resolveIconAlias's fallback for a stale/unknown icon alias",
			"TagRegistryModal.ts / TagPickerModal.ts — \"+ New tag\" row's placeholder icon before one is picked",
		],
	},
	{ id: ICON_SHOP, label: "Shop", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{
		id: ICON_SETTINGS_GEAR,
		label: "Settings (gear)",
		source: "custom",
		usedIn: ["iconRegistry.ts — Codex icon catalog (distinct from ICON_FILTER's funnel-lines glyph)"],
	},
	{ id: ICON_FIRE, label: "Fire", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_CROWN, label: "Crown", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{
		id: ICON_CALENDAR_PLAIN,
		label: "Calendar (plain)",
		source: "custom",
		usedIn: ["iconRegistry.ts — Codex icon catalog (distinct from ICON_CALENDAR's dotted variant)"],
	},
	{ id: ICON_BUILDING_A, label: "Building A", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_BUILDING_B, label: "Building B", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{
		id: ICON_BOOKMARK,
		label: "Bookmark",
		source: "custom",
		usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog", "iconRegistry.ts — Codex icon catalog"],
	},
	{
		id: ICON_BOOKMARK_FILL,
		label: "Bookmark (filled)",
		source: "custom",
		usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog", "iconRegistry.ts — Codex icon catalog"],
	},
	{ id: ICON_TRUCK, label: "Truck", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_ROCKETSHIP, label: "Rocketship", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_PLANE, label: "Plane", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_SHIP, label: "Ship", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_ROAD, label: "Road", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_MOUNTAIN, label: "Mountain", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{
		id: ICON_TOWER_BLOCK,
		label: "Tower (block)",
		source: "custom",
		usedIn: ["iconRegistry.ts — Codex icon catalog (one of three tower variants — block/slim/fortress)"],
	},
	{
		id: ICON_TOWER_SLIM,
		label: "Tower (slim)",
		source: "custom",
		usedIn: ["iconRegistry.ts — Codex icon catalog (one of three tower variants — block/slim/fortress)"],
	},
	{
		id: ICON_TOWER_FORTRESS,
		label: "Tower (fortress)",
		source: "custom",
		usedIn: ["iconRegistry.ts — Codex icon catalog (one of three tower variants — block/slim/fortress)"],
	},
	{ id: ICON_SHIELD, label: "Shield", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{
		id: ICON_GEARS,
		label: "Gears",
		source: "custom",
		usedIn: ["iconRegistry.ts — Codex icon catalog (two interlocking gears, distinct from ICON_SETTINGS_GEAR's single gear)"],
	},
	{ id: ICON_EXPLOSION, label: "Explosion", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{
		id: ICON_SWORDS_CROSSED,
		label: "Swords (crossed)",
		source: "custom",
		usedIn: ["iconRegistry.ts — Codex icon catalog (distinct from ICON_SWORD's single blade)"],
	},
	{ id: ICON_SWORD, label: "Sword", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_AXE, label: "Axe", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_MAGIC_WAND, label: "Magic wand", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_SUN_FILL, label: "Sun (filled)", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_THUNDERSTORM, label: "Thunderstorm", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_SNOW, label: "Snow", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_RAIN, label: "Rain", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_RIVER, label: "River", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_DEAD_TREE, label: "Dead tree", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_PINE_TREE, label: "Pine tree", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_TREE, label: "Tree", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_BOWL_RICE, label: "Bowl of rice", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_BOWL, label: "Bowl", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_EGG, label: "Egg", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_DRAGON, label: "Dragon", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_UNICORN, label: "Unicorn", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_FISH, label: "Fish", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_PAW, label: "Paw print", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_SKULL, label: "Skull", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{ id: ICON_MUSIC_NOTE, label: "Music note", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{
		id: ICON_SPEECH_BUBBLE,
		label: "Speech bubble",
		source: "custom",
		usedIn: ["iconRegistry.ts — Codex icon catalog (distinct from ICON_MESSAGE's message-bubble glyph)"],
	},
	{ id: ICON_SCROLL, label: "Scroll", source: "custom", usedIn: ["iconRegistry.ts — Codex icon catalog"] },
	{
		id: ICON_CHECK_CIRCLE,
		label: "Circle tick",
		source: "custom",
		usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog (replaced the stock \"check-circle\" Lucide icon formerly in that catalog)"],
	},
	{ id: ICON_CHECK_CIRCLE_FILL, label: "Circle tick (filled)", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{
		id: ICON_FLAG,
		label: "Flag",
		source: "custom",
		usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog (replaced the stock \"flag\" Lucide icon formerly in that catalog)"],
	},
	{ id: ICON_FLAG_FILL, label: "Flag (filled)", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{
		id: ICON_STAR_OUTLINE,
		label: "Star (outline)",
		source: "custom",
		usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog (replaced the stock \"star\" Lucide icon formerly in that catalog)"],
	},
	{ id: ICON_STAR_FILL, label: "Star (filled)", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{ id: ICON_STAR_DUOTONE, label: "Star (duotone)", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{
		id: ICON_LOCK,
		label: "Lock",
		source: "custom",
		usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog (replaced the stock \"lock\" Lucide icon formerly in that catalog)"],
	},
	{ id: ICON_HEART_CIRCLE, label: "Heart circle (outline)", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{ id: ICON_HEART_CIRCLE_FILL, label: "Heart circle (filled)", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{ id: ICON_HEART_OUTLINE, label: "Heart (outline)", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{ id: ICON_HEART_FILL, label: "Heart (filled)", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },
	{ id: ICON_MESSAGE, label: "Message", source: "custom", usedIn: ["iconRegistry.ts — chapter/novel tag icon catalog"] },

	// Stock (Lucide icons bundled with Obsidian, referenced by name)
	{
		id: "grip-vertical",
		label: "Drag handle",
		source: "lucide",
		usedIn: [
			"SeriesModal.ts — book row drag handle",
			"TopPanel.ts — row drag handle",
			"TagRegistryModal.ts / TagPickerModal.ts — tag row drag handle",
			// BottomPanel.ts no longer has one — the Codex tree's whole row is now the drag target
			// (dragReorderTree.ts), not a grip handle. See that file's revertable-feature-test note.
		],
	},
	{
		id: "chevron-right",
		label: "Collapsed section",
		source: "lucide",
		usedIn: ["BottomPanel.ts — Codex folder collapse chevron"],
	},
	{
		id: "chevron-down",
		label: "Expanded section",
		source: "lucide",
		usedIn: ["BottomPanel.ts — Codex folder collapse chevron"],
	},
];
